// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/domain/entity"
)

// NewMockACLRepository creates a new instance of MockACLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockACLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockACLRepository {
	mock := &MockACLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockACLRepository is an autogenerated mock type for the ACLRepository type
type MockACLRepository struct {
	mock.Mock
}

type MockACLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockACLRepository) EXPECT() *MockACLRepository_Expecter {
	return &MockACLRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockACLRepository
func (_mock *MockACLRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockACLRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockACLRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockACLRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockACLRepository_Delete_Call {
	return &MockACLRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockACLRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockACLRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockACLRepository_Delete_Call) Return(err error) *MockACLRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockACLRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockACLRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByResource provides a mock function for the type MockACLRepository
func (_mock *MockACLRepository) DeleteByResource(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID) error {
	ret := _mock.Called(ctx, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ResourceType, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, resourceType, resourceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockACLRepository_DeleteByResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByResource'
type MockACLRepository_DeleteByResource_Call struct {
	*mock.Call
}

// DeleteByResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType entity.ResourceType
//   - resourceID uuid.UUID
func (_e *MockACLRepository_Expecter) DeleteByResource(ctx interface{}, resourceType interface{}, resourceID interface{}) *MockACLRepository_DeleteByResource_Call {
	return &MockACLRepository_DeleteByResource_Call{Call: _e.mock.On("DeleteByResource", ctx, resourceType, resourceID)}
}

func (_c *MockACLRepository_DeleteByResource_Call) Run(run func(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID)) *MockACLRepository_DeleteByResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ResourceType
		if args[1] != nil {
			arg1 = args[1].(entity.ResourceType)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockACLRepository_DeleteByResource_Call) Return(err error) *MockACLRepository_DeleteByResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockACLRepository_DeleteByResource_Call) RunAndReturn(run func(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID) error) *MockACLRepository_DeleteByResource_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResource provides a mock function for the type MockACLRepository
func (_mock *MockACLRepository) FindByResource(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID) ([]*entity.ACLEntry, error) {
	ret := _mock.Called(ctx, resourceType, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for FindByResource")
	}

	var r0 []*entity.ACLEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ResourceType, uuid.UUID) ([]*entity.ACLEntry, error)); ok {
		return returnFunc(ctx, resourceType, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ResourceType, uuid.UUID) []*entity.ACLEntry); ok {
		r0 = returnFunc(ctx, resourceType, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ACLEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ResourceType, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, resourceType, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockACLRepository_FindByResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResource'
type MockACLRepository_FindByResource_Call struct {
	*mock.Call
}

// FindByResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType entity.ResourceType
//   - resourceID uuid.UUID
func (_e *MockACLRepository_Expecter) FindByResource(ctx interface{}, resourceType interface{}, resourceID interface{}) *MockACLRepository_FindByResource_Call {
	return &MockACLRepository_FindByResource_Call{Call: _e.mock.On("FindByResource", ctx, resourceType, resourceID)}
}

func (_c *MockACLRepository_FindByResource_Call) Run(run func(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID)) *MockACLRepository_FindByResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ResourceType
		if args[1] != nil {
			arg1 = args[1].(entity.ResourceType)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockACLRepository_FindByResource_Call) Return(aCLEntrys []*entity.ACLEntry, err error) *MockACLRepository_FindByResource_Call {
	_c.Call.Return(aCLEntrys, err)
	return _c
}

func (_c *MockACLRepository_FindByResource_Call) RunAndReturn(run func(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID) ([]*entity.ACLEntry, error)) *MockACLRepository_FindByResource_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySubject provides a mock function for the type MockACLRepository
func (_mock *MockACLRepository) FindBySubject(ctx context.Context, subjectType entity.ACLSubjectType, subjectID uuid.UUID) ([]*entity.ACLEntry, error) {
	ret := _mock.Called(ctx, subjectType, subjectID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySubject")
	}

	var r0 []*entity.ACLEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ACLSubjectType, uuid.UUID) ([]*entity.ACLEntry, error)); ok {
		return returnFunc(ctx, subjectType, subjectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ACLSubjectType, uuid.UUID) []*entity.ACLEntry); ok {
		r0 = returnFunc(ctx, subjectType, subjectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ACLEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ACLSubjectType, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, subjectType, subjectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockACLRepository_FindBySubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySubject'
type MockACLRepository_FindBySubject_Call struct {
	*mock.Call
}

// FindBySubject is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectType entity.ACLSubjectType
//   - subjectID uuid.UUID
func (_e *MockACLRepository_Expecter) FindBySubject(ctx interface{}, subjectType interface{}, subjectID interface{}) *MockACLRepository_FindBySubject_Call {
	return &MockACLRepository_FindBySubject_Call{Call: _e.mock.On("FindBySubject", ctx, subjectType, subjectID)}
}

func (_c *MockACLRepository_FindBySubject_Call) Run(run func(ctx context.Context, subjectType entity.ACLSubjectType, subjectID uuid.UUID)) *MockACLRepository_FindBySubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ACLSubjectType
		if args[1] != nil {
			arg1 = args[1].(entity.ACLSubjectType)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockACLRepository_FindBySubject_Call) Return(aCLEntrys []*entity.ACLEntry, err error) *MockACLRepository_FindBySubject_Call {
	_c.Call.Return(aCLEntrys, err)
	return _c
}

func (_c *MockACLRepository_FindBySubject_Call) RunAndReturn(run func(ctx context.Context, subjectType entity.ACLSubjectType, subjectID uuid.UUID) ([]*entity.ACLEntry, error)) *MockACLRepository_FindBySubject_Call {
	_c.Call.Return(run)
	return _c
}

// HasPermission provides a mock function for the type MockACLRepository
func (_mock *MockACLRepository) HasPermission(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID, subjectType entity.ACLSubjectType, subjectID uuid.UUID, permission entity.ACLPermission) (bool, error) {
	ret := _mock.Called(ctx, resourceType, resourceID, subjectType, subjectID, permission)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ResourceType, uuid.UUID, entity.ACLSubjectType, uuid.UUID, entity.ACLPermission) (bool, error)); ok {
		return returnFunc(ctx, resourceType, resourceID, subjectType, subjectID, permission)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.ResourceType, uuid.UUID, entity.ACLSubjectType, uuid.UUID, entity.ACLPermission) bool); ok {
		r0 = returnFunc(ctx, resourceType, resourceID, subjectType, subjectID, permission)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.ResourceType, uuid.UUID, entity.ACLSubjectType, uuid.UUID, entity.ACLPermission) error); ok {
		r1 = returnFunc(ctx, resourceType, resourceID, subjectType, subjectID, permission)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockACLRepository_HasPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPermission'
type MockACLRepository_HasPermission_Call struct {
	*mock.Call
}

// HasPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType entity.ResourceType
//   - resourceID uuid.UUID
//   - subjectType entity.ACLSubjectType
//   - subjectID uuid.UUID
//   - permission entity.ACLPermission
func (_e *MockACLRepository_Expecter) HasPermission(ctx interface{}, resourceType interface{}, resourceID interface{}, subjectType interface{}, subjectID interface{}, permission interface{}) *MockACLRepository_HasPermission_Call {
	return &MockACLRepository_HasPermission_Call{Call: _e.mock.On("HasPermission", ctx, resourceType, resourceID, subjectType, subjectID, permission)}
}

func (_c *MockACLRepository_HasPermission_Call) Run(run func(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID, subjectType entity.ACLSubjectType, subjectID uuid.UUID, permission entity.ACLPermission)) *MockACLRepository_HasPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.ResourceType
		if args[1] != nil {
			arg1 = args[1].(entity.ResourceType)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 entity.ACLSubjectType
		if args[3] != nil {
			arg3 = args[3].(entity.ACLSubjectType)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		var arg5 entity.ACLPermission
		if args[5] != nil {
			arg5 = args[5].(entity.ACLPermission)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockACLRepository_HasPermission_Call) Return(b bool, err error) *MockACLRepository_HasPermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockACLRepository_HasPermission_Call) RunAndReturn(run func(ctx context.Context, resourceType entity.ResourceType, resourceID uuid.UUID, subjectType entity.ACLSubjectType, subjectID uuid.UUID, permission entity.ACLPermission) (bool, error)) *MockACLRepository_HasPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockACLRepository
func (_mock *MockACLRepository) Save(ctx context.Context, entry *entity.ACLEntry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.ACLEntry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockACLRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockACLRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *entity.ACLEntry
func (_e *MockACLRepository_Expecter) Save(ctx interface{}, entry interface{}) *MockACLRepository_Save_Call {
	return &MockACLRepository_Save_Call{Call: _e.mock.On("Save", ctx, entry)}
}

func (_c *MockACLRepository_Save_Call) Run(run func(ctx context.Context, entry *entity.ACLEntry)) *MockACLRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.ACLEntry
		if args[1] != nil {
			arg1 = args[1].(*entity.ACLEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockACLRepository_Save_Call) Return(err error) *MockACLRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockACLRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entry *entity.ACLEntry) error) *MockACLRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
