// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/dto"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ChangePassword(ctx context.Context, userID uuid.UUID, input dto.ChangePasswordInput) error {
	ret := _mock.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ChangePasswordInput) error); ok {
		r0 = returnFunc(ctx, userID, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAuthService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input dto.ChangePasswordInput
func (_e *MockAuthService_Expecter) ChangePassword(ctx interface{}, userID interface{}, input interface{}) *MockAuthService_ChangePassword_Call {
	return &MockAuthService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, input)}
}

func (_c *MockAuthService_ChangePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, input dto.ChangePasswordInput)) *MockAuthService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.ChangePasswordInput
		if args[2] != nil {
			arg2 = args[2].(dto.ChangePasswordInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_ChangePassword_Call) Return(err error) *MockAuthService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, input dto.ChangePasswordInput) error) *MockAuthService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, input dto.LoginInput) (*dto.AuthOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.AuthOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.LoginInput) (*dto.AuthOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.LoginInput) *dto.AuthOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuthOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.LoginInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.LoginInput
func (_e *MockAuthService_Expecter) Login(ctx interface{}, input interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, input dto.LoginInput)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.LoginInput
		if args[1] != nil {
			arg1 = args[1].(dto.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(authOutput *dto.AuthOutput, err error) *MockAuthService_Login_Call {
	_c.Call.Return(authOutput, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, input dto.LoginInput) (*dto.AuthOutput, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, userID uuid.UUID, accessToken string) error {
	ret := _mock.Called(ctx, userID, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, accessToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - accessToken string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, userID interface{}, accessToken interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, userID, accessToken)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, userID uuid.UUID, accessToken string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, accessToken string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshToken(ctx context.Context, refreshToken string) (*dto.AuthOutput, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.AuthOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.AuthOutput, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.AuthOutput); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuthOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(authOutput *dto.AuthOutput, err error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(authOutput, err)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*dto.AuthOutput, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, input dto.CreateUserInput) (*dto.AuthOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.AuthOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateUserInput) (*dto.AuthOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateUserInput) *dto.AuthOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuthOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateUserInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateUserInput
func (_e *MockAuthService_Expecter) Register(ctx interface{}, input interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, input)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, input dto.CreateUserInput)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateUserInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(authOutput *dto.AuthOutput, err error) *MockAuthService_Register_Call {
	_c.Call.Return(authOutput, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateUserInput) (*dto.AuthOutput, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ValidateToken(ctx context.Context, token string) (*dto.TokenClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *dto.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.TokenClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.TokenClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockAuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) ValidateToken(ctx interface{}, token interface{}) *MockAuthService_ValidateToken_Call {
	return &MockAuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *MockAuthService_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) Return(tokenClaims *dto.TokenClaims, err error) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*dto.TokenClaims, error)) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
