// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/domain/event"
)

// NewMockEventSubscriber creates a new instance of MockEventSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSubscriber {
	mock := &MockEventSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventSubscriber is an autogenerated mock type for the EventSubscriber type
type MockEventSubscriber struct {
	mock.Mock
}

type MockEventSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventSubscriber) EXPECT() *MockEventSubscriber_Expecter {
	return &MockEventSubscriber_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockEventSubscriber
func (_mock *MockEventSubscriber) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSubscriber_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventSubscriber_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEventSubscriber_Expecter) Close() *MockEventSubscriber_Close_Call {
	return &MockEventSubscriber_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEventSubscriber_Close_Call) Run(run func()) *MockEventSubscriber_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSubscriber_Close_Call) Return(err error) *MockEventSubscriber_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSubscriber_Close_Call) RunAndReturn(run func() error) *MockEventSubscriber_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockEventSubscriber
func (_mock *MockEventSubscriber) Subscribe(ctx context.Context, topic string, groupID string) (<-chan event.Event, error) {
	ret := _mock.Called(ctx, topic, groupID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan event.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (<-chan event.Event, error)); ok {
		return returnFunc(ctx, topic, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) <-chan event.Event); ok {
		r0 = returnFunc(ctx, topic, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan event.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, topic, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - groupID string
func (_e *MockEventSubscriber_Expecter) Subscribe(ctx interface{}, topic interface{}, groupID interface{}) *MockEventSubscriber_Subscribe_Call {
	return &MockEventSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topic, groupID)}
}

func (_c *MockEventSubscriber_Subscribe_Call) Run(run func(ctx context.Context, topic string, groupID string)) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call) Return(eventCh <-chan event.Event, err error) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Return(eventCh, err)
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call) RunAndReturn(run func(ctx context.Context, topic string, groupID string) (<-chan event.Event, error)) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type MockEventSubscriber
func (_mock *MockEventSubscriber) Unsubscribe(ctx context.Context, topic string) error {
	ret := _mock.Called(ctx, topic)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, topic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSubscriber_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockEventSubscriber_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
func (_e *MockEventSubscriber_Expecter) Unsubscribe(ctx interface{}, topic interface{}) *MockEventSubscriber_Unsubscribe_Call {
	return &MockEventSubscriber_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx, topic)}
}

func (_c *MockEventSubscriber_Unsubscribe_Call) Run(run func(ctx context.Context, topic string)) *MockEventSubscriber_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriber_Unsubscribe_Call) Return(err error) *MockEventSubscriber_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSubscriber_Unsubscribe_Call) RunAndReturn(run func(ctx context.Context, topic string) error) *MockEventSubscriber_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
