// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/port/output"
)

// NewMockFileStorage creates a new instance of MockFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorage {
	mock := &MockFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileStorage is an autogenerated mock type for the FileStorage type
type MockFileStorage struct {
	mock.Mock
}

type MockFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorage) EXPECT() *MockFileStorage_Expecter {
	return &MockFileStorage_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) Copy(ctx context.Context, sourceKey string, destKey string) (*output.FileMetadata, error) {
	ret := _mock.Called(ctx, sourceKey, destKey)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 *output.FileMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*output.FileMetadata, error)); ok {
		return returnFunc(ctx, sourceKey, destKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *output.FileMetadata); ok {
		r0 = returnFunc(ctx, sourceKey, destKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.FileMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, sourceKey, destKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockFileStorage_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceKey string
//   - destKey string
func (_e *MockFileStorage_Expecter) Copy(ctx interface{}, sourceKey interface{}, destKey interface{}) *MockFileStorage_Copy_Call {
	return &MockFileStorage_Copy_Call{Call: _e.mock.On("Copy", ctx, sourceKey, destKey)}
}

func (_c *MockFileStorage_Copy_Call) Run(run func(ctx context.Context, sourceKey string, destKey string)) *MockFileStorage_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileStorage_Copy_Call) Return(fileMetadata *output.FileMetadata, err error) *MockFileStorage_Copy_Call {
	_c.Call.Return(fileMetadata, err)
	return _c
}

func (_c *MockFileStorage_Copy_Call) RunAndReturn(run func(ctx context.Context, sourceKey string, destKey string) (*output.FileMetadata, error)) *MockFileStorage_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFileStorage_Expecter) Delete(ctx interface{}, key interface{}) *MockFileStorage_Delete_Call {
	return &MockFileStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockFileStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockFileStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStorage_Delete_Call) Return(err error) *MockFileStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockFileStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) Download(ctx context.Context, key string) (io.ReadCloser, *output.FileMetadata, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 *output.FileMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, *output.FileMetadata, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *output.FileMetadata); ok {
		r1 = returnFunc(ctx, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*output.FileMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFileStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockFileStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFileStorage_Expecter) Download(ctx interface{}, key interface{}) *MockFileStorage_Download_Call {
	return &MockFileStorage_Download_Call{Call: _e.mock.On("Download", ctx, key)}
}

func (_c *MockFileStorage_Download_Call) Run(run func(ctx context.Context, key string)) *MockFileStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStorage_Download_Call) Return(readCloser io.ReadCloser, fileMetadata *output.FileMetadata, err error) *MockFileStorage_Download_Call {
	_c.Call.Return(readCloser, fileMetadata, err)
	return _c
}

func (_c *MockFileStorage_Download_Call) RunAndReturn(run func(ctx context.Context, key string) (io.ReadCloser, *output.FileMetadata, error)) *MockFileStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) Exists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockFileStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFileStorage_Expecter) Exists(ctx interface{}, key interface{}) *MockFileStorage_Exists_Call {
	return &MockFileStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockFileStorage_Exists_Call) Run(run func(ctx context.Context, key string)) *MockFileStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStorage_Exists_Call) Return(b bool, err error) *MockFileStorage_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFileStorage_Exists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockFileStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePresignedURL provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) GeneratePresignedURL(ctx context.Context, key string, expiration time.Duration) (string, error) {
	ret := _mock.Called(ctx, key, expiration)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, key, expiration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, key, expiration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, expiration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_GeneratePresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePresignedURL'
type MockFileStorage_GeneratePresignedURL_Call struct {
	*mock.Call
}

// GeneratePresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiration time.Duration
func (_e *MockFileStorage_Expecter) GeneratePresignedURL(ctx interface{}, key interface{}, expiration interface{}) *MockFileStorage_GeneratePresignedURL_Call {
	return &MockFileStorage_GeneratePresignedURL_Call{Call: _e.mock.On("GeneratePresignedURL", ctx, key, expiration)}
}

func (_c *MockFileStorage_GeneratePresignedURL_Call) Run(run func(ctx context.Context, key string, expiration time.Duration)) *MockFileStorage_GeneratePresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileStorage_GeneratePresignedURL_Call) Return(s string, err error) *MockFileStorage_GeneratePresignedURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileStorage_GeneratePresignedURL_Call) RunAndReturn(run func(ctx context.Context, key string, expiration time.Duration) (string, error)) *MockFileStorage_GeneratePresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateUploadURL provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) GenerateUploadURL(ctx context.Context, key string, contentType string, expiration time.Duration) (string, error) {
	ret := _mock.Called(ctx, key, contentType, expiration)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUploadURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, key, contentType, expiration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, key, contentType, expiration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, contentType, expiration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_GenerateUploadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateUploadURL'
type MockFileStorage_GenerateUploadURL_Call struct {
	*mock.Call
}

// GenerateUploadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - expiration time.Duration
func (_e *MockFileStorage_Expecter) GenerateUploadURL(ctx interface{}, key interface{}, contentType interface{}, expiration interface{}) *MockFileStorage_GenerateUploadURL_Call {
	return &MockFileStorage_GenerateUploadURL_Call{Call: _e.mock.On("GenerateUploadURL", ctx, key, contentType, expiration)}
}

func (_c *MockFileStorage_GenerateUploadURL_Call) Run(run func(ctx context.Context, key string, contentType string, expiration time.Duration)) *MockFileStorage_GenerateUploadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileStorage_GenerateUploadURL_Call) Return(s string, err error) *MockFileStorage_GenerateUploadURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileStorage_GenerateUploadURL_Call) RunAndReturn(run func(ctx context.Context, key string, contentType string, expiration time.Duration) (string, error)) *MockFileStorage_GenerateUploadURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) GetMetadata(ctx context.Context, key string) (*output.FileMetadata, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *output.FileMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*output.FileMetadata, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *output.FileMetadata); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.FileMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockFileStorage_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFileStorage_Expecter) GetMetadata(ctx interface{}, key interface{}) *MockFileStorage_GetMetadata_Call {
	return &MockFileStorage_GetMetadata_Call{Call: _e.mock.On("GetMetadata", ctx, key)}
}

func (_c *MockFileStorage_GetMetadata_Call) Run(run func(ctx context.Context, key string)) *MockFileStorage_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileStorage_GetMetadata_Call) Return(fileMetadata *output.FileMetadata, err error) *MockFileStorage_GetMetadata_Call {
	_c.Call.Return(fileMetadata, err)
	return _c
}

func (_c *MockFileStorage_GetMetadata_Call) RunAndReturn(run func(ctx context.Context, key string) (*output.FileMetadata, error)) *MockFileStorage_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) List(ctx context.Context, prefix string, maxKeys int) ([]*output.FileMetadata, error) {
	ret := _mock.Called(ctx, prefix, maxKeys)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*output.FileMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]*output.FileMetadata, error)); ok {
		return returnFunc(ctx, prefix, maxKeys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []*output.FileMetadata); ok {
		r0 = returnFunc(ctx, prefix, maxKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*output.FileMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, prefix, maxKeys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFileStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - maxKeys int
func (_e *MockFileStorage_Expecter) List(ctx interface{}, prefix interface{}, maxKeys interface{}) *MockFileStorage_List_Call {
	return &MockFileStorage_List_Call{Call: _e.mock.On("List", ctx, prefix, maxKeys)}
}

func (_c *MockFileStorage_List_Call) Run(run func(ctx context.Context, prefix string, maxKeys int)) *MockFileStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileStorage_List_Call) Return(fileMetadatas []*output.FileMetadata, err error) *MockFileStorage_List_Call {
	_c.Call.Return(fileMetadatas, err)
	return _c
}

func (_c *MockFileStorage_List_Call) RunAndReturn(run func(ctx context.Context, prefix string, maxKeys int) ([]*output.FileMetadata, error)) *MockFileStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockFileStorage
func (_mock *MockFileStorage) Upload(ctx context.Context, key string, reader io.Reader, options output.UploadOptions) (*output.FileMetadata, error) {
	ret := _mock.Called(ctx, key, reader, options)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *output.FileMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, output.UploadOptions) (*output.FileMetadata, error)); ok {
		return returnFunc(ctx, key, reader, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, output.UploadOptions) *output.FileMetadata); ok {
		r0 = returnFunc(ctx, key, reader, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.FileMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, output.UploadOptions) error); ok {
		r1 = returnFunc(ctx, key, reader, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockFileStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - reader io.Reader
//   - options output.UploadOptions
func (_e *MockFileStorage_Expecter) Upload(ctx interface{}, key interface{}, reader interface{}, options interface{}) *MockFileStorage_Upload_Call {
	return &MockFileStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, key, reader, options)}
}

func (_c *MockFileStorage_Upload_Call) Run(run func(ctx context.Context, key string, reader io.Reader, options output.UploadOptions)) *MockFileStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 output.UploadOptions
		if args[3] != nil {
			arg3 = args[3].(output.UploadOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileStorage_Upload_Call) Return(fileMetadata *output.FileMetadata, err error) *MockFileStorage_Upload_Call {
	_c.Call.Return(fileMetadata, err)
	return _c
}

func (_c *MockFileStorage_Upload_Call) RunAndReturn(run func(ctx context.Context, key string, reader io.Reader, options output.UploadOptions) (*output.FileMetadata, error)) *MockFileStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}
