// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/dto"
)

// NewMockLabelService creates a new instance of MockLabelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLabelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLabelService {
	mock := &MockLabelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLabelService is an autogenerated mock type for the LabelService type
type MockLabelService struct {
	mock.Mock
}

type MockLabelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLabelService) EXPECT() *MockLabelService_Expecter {
	return &MockLabelService_Expecter{mock: &_m.Mock}
}

// CreateLabel provides a mock function for the type MockLabelService
func (_mock *MockLabelService) CreateLabel(ctx context.Context, input dto.CreateLabelInput) (*dto.LabelOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateLabel")
	}

	var r0 *dto.LabelOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateLabelInput) (*dto.LabelOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateLabelInput) *dto.LabelOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LabelOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateLabelInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelService_CreateLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLabel'
type MockLabelService_CreateLabel_Call struct {
	*mock.Call
}

// CreateLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateLabelInput
func (_e *MockLabelService_Expecter) CreateLabel(ctx interface{}, input interface{}) *MockLabelService_CreateLabel_Call {
	return &MockLabelService_CreateLabel_Call{Call: _e.mock.On("CreateLabel", ctx, input)}
}

func (_c *MockLabelService_CreateLabel_Call) Run(run func(ctx context.Context, input dto.CreateLabelInput)) *MockLabelService_CreateLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateLabelInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateLabelInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelService_CreateLabel_Call) Return(labelOutput *dto.LabelOutput, err error) *MockLabelService_CreateLabel_Call {
	_c.Call.Return(labelOutput, err)
	return _c
}

func (_c *MockLabelService_CreateLabel_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateLabelInput) (*dto.LabelOutput, error)) *MockLabelService_CreateLabel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLabel provides a mock function for the type MockLabelService
func (_mock *MockLabelService) DeleteLabel(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLabelService_DeleteLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLabel'
type MockLabelService_DeleteLabel_Call struct {
	*mock.Call
}

// DeleteLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLabelService_Expecter) DeleteLabel(ctx interface{}, id interface{}) *MockLabelService_DeleteLabel_Call {
	return &MockLabelService_DeleteLabel_Call{Call: _e.mock.On("DeleteLabel", ctx, id)}
}

func (_c *MockLabelService_DeleteLabel_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLabelService_DeleteLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelService_DeleteLabel_Call) Return(err error) *MockLabelService_DeleteLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLabelService_DeleteLabel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockLabelService_DeleteLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetLabel provides a mock function for the type MockLabelService
func (_mock *MockLabelService) GetLabel(ctx context.Context, id uuid.UUID) (*dto.LabelOutput, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLabel")
	}

	var r0 *dto.LabelOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.LabelOutput, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.LabelOutput); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LabelOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelService_GetLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLabel'
type MockLabelService_GetLabel_Call struct {
	*mock.Call
}

// GetLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLabelService_Expecter) GetLabel(ctx interface{}, id interface{}) *MockLabelService_GetLabel_Call {
	return &MockLabelService_GetLabel_Call{Call: _e.mock.On("GetLabel", ctx, id)}
}

func (_c *MockLabelService_GetLabel_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLabelService_GetLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelService_GetLabel_Call) Return(labelOutput *dto.LabelOutput, err error) *MockLabelService_GetLabel_Call {
	_c.Call.Return(labelOutput, err)
	return _c
}

func (_c *MockLabelService_GetLabel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*dto.LabelOutput, error)) *MockLabelService_GetLabel_Call {
	_c.Call.Return(run)
	return _c
}

// ListLabels provides a mock function for the type MockLabelService
func (_mock *MockLabelService) ListLabels(ctx context.Context) ([]*dto.LabelOutput, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListLabels")
	}

	var r0 []*dto.LabelOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*dto.LabelOutput, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*dto.LabelOutput); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.LabelOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelService_ListLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLabels'
type MockLabelService_ListLabels_Call struct {
	*mock.Call
}

// ListLabels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLabelService_Expecter) ListLabels(ctx interface{}) *MockLabelService_ListLabels_Call {
	return &MockLabelService_ListLabels_Call{Call: _e.mock.On("ListLabels", ctx)}
}

func (_c *MockLabelService_ListLabels_Call) Run(run func(ctx context.Context)) *MockLabelService_ListLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLabelService_ListLabels_Call) Return(labelOutputs []*dto.LabelOutput, err error) *MockLabelService_ListLabels_Call {
	_c.Call.Return(labelOutputs, err)
	return _c
}

func (_c *MockLabelService_ListLabels_Call) RunAndReturn(run func(ctx context.Context) ([]*dto.LabelOutput, error)) *MockLabelService_ListLabels_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLabel provides a mock function for the type MockLabelService
func (_mock *MockLabelService) UpdateLabel(ctx context.Context, id uuid.UUID, input dto.UpdateLabelInput) (*dto.LabelOutput, error) {
	ret := _mock.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLabel")
	}

	var r0 *dto.LabelOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateLabelInput) (*dto.LabelOutput, error)); ok {
		return returnFunc(ctx, id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateLabelInput) *dto.LabelOutput); ok {
		r0 = returnFunc(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LabelOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateLabelInput) error); ok {
		r1 = returnFunc(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelService_UpdateLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLabel'
type MockLabelService_UpdateLabel_Call struct {
	*mock.Call
}

// UpdateLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input dto.UpdateLabelInput
func (_e *MockLabelService_Expecter) UpdateLabel(ctx interface{}, id interface{}, input interface{}) *MockLabelService_UpdateLabel_Call {
	return &MockLabelService_UpdateLabel_Call{Call: _e.mock.On("UpdateLabel", ctx, id, input)}
}

func (_c *MockLabelService_UpdateLabel_Call) Run(run func(ctx context.Context, id uuid.UUID, input dto.UpdateLabelInput)) *MockLabelService_UpdateLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.UpdateLabelInput
		if args[2] != nil {
			arg2 = args[2].(dto.UpdateLabelInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLabelService_UpdateLabel_Call) Return(labelOutput *dto.LabelOutput, err error) *MockLabelService_UpdateLabel_Call {
	_c.Call.Return(labelOutput, err)
	return _c
}

func (_c *MockLabelService_UpdateLabel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, input dto.UpdateLabelInput) (*dto.LabelOutput, error)) *MockLabelService_UpdateLabel_Call {
	_c.Call.Return(run)
	return _c
}
