// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/domain/entity"
)

// NewMockLabelRepository creates a new instance of MockLabelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLabelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLabelRepository {
	mock := &MockLabelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLabelRepository is an autogenerated mock type for the LabelRepository type
type MockLabelRepository struct {
	mock.Mock
}

type MockLabelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLabelRepository) EXPECT() *MockLabelRepository_Expecter {
	return &MockLabelRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLabelRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLabelRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLabelRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockLabelRepository_Delete_Call {
	return &MockLabelRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockLabelRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLabelRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelRepository_Delete_Call) Return(err error) *MockLabelRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLabelRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockLabelRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByID provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) ExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelRepository_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockLabelRepository_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLabelRepository_Expecter) ExistsByID(ctx interface{}, id interface{}) *MockLabelRepository_ExistsByID_Call {
	return &MockLabelRepository_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, id)}
}

func (_c *MockLabelRepository_ExistsByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLabelRepository_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelRepository_ExistsByID_Call) Return(b bool, err error) *MockLabelRepository_ExistsByID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockLabelRepository_ExistsByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockLabelRepository_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) FindAll(ctx context.Context) ([]*entity.Label, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Label
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Label, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Label); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Label)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockLabelRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLabelRepository_Expecter) FindAll(ctx interface{}) *MockLabelRepository_FindAll_Call {
	return &MockLabelRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockLabelRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockLabelRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLabelRepository_FindAll_Call) Return(labels []*entity.Label, err error) *MockLabelRepository_FindAll_Call {
	_c.Call.Return(labels, err)
	return _c
}

func (_c *MockLabelRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Label, error)) *MockLabelRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Label, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Label
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Label, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Label); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Label)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockLabelRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLabelRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockLabelRepository_FindByID_Call {
	return &MockLabelRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockLabelRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLabelRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelRepository_FindByID_Call) Return(label *entity.Label, err error) *MockLabelRepository_FindByID_Call {
	_c.Call.Return(label, err)
	return _c
}

func (_c *MockLabelRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Label, error)) *MockLabelRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) FindByName(ctx context.Context, name string) (*entity.Label, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.Label
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Label, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Label); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Label)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockLabelRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockLabelRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockLabelRepository_FindByName_Call {
	return &MockLabelRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockLabelRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockLabelRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelRepository_FindByName_Call) Return(label *entity.Label, err error) *MockLabelRepository_FindByName_Call {
	_c.Call.Return(label, err)
	return _c
}

func (_c *MockLabelRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Label, error)) *MockLabelRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTaskID provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) FindByTaskID(ctx context.Context, taskID uuid.UUID) ([]*entity.Label, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTaskID")
	}

	var r0 []*entity.Label
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Label, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Label); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Label)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLabelRepository_FindByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTaskID'
type MockLabelRepository_FindByTaskID_Call struct {
	*mock.Call
}

// FindByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
func (_e *MockLabelRepository_Expecter) FindByTaskID(ctx interface{}, taskID interface{}) *MockLabelRepository_FindByTaskID_Call {
	return &MockLabelRepository_FindByTaskID_Call{Call: _e.mock.On("FindByTaskID", ctx, taskID)}
}

func (_c *MockLabelRepository_FindByTaskID_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockLabelRepository_FindByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelRepository_FindByTaskID_Call) Return(labels []*entity.Label, err error) *MockLabelRepository_FindByTaskID_Call {
	_c.Call.Return(labels, err)
	return _c
}

func (_c *MockLabelRepository_FindByTaskID_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) ([]*entity.Label, error)) *MockLabelRepository_FindByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) Save(ctx context.Context, label *entity.Label) error {
	ret := _mock.Called(ctx, label)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Label) error); ok {
		r0 = returnFunc(ctx, label)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLabelRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLabelRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - label *entity.Label
func (_e *MockLabelRepository_Expecter) Save(ctx interface{}, label interface{}) *MockLabelRepository_Save_Call {
	return &MockLabelRepository_Save_Call{Call: _e.mock.On("Save", ctx, label)}
}

func (_c *MockLabelRepository_Save_Call) Run(run func(ctx context.Context, label *entity.Label)) *MockLabelRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Label
		if args[1] != nil {
			arg1 = args[1].(*entity.Label)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelRepository_Save_Call) Return(err error) *MockLabelRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLabelRepository_Save_Call) RunAndReturn(run func(ctx context.Context, label *entity.Label) error) *MockLabelRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockLabelRepository
func (_mock *MockLabelRepository) Update(ctx context.Context, label *entity.Label) error {
	ret := _mock.Called(ctx, label)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Label) error); ok {
		r0 = returnFunc(ctx, label)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLabelRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLabelRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - label *entity.Label
func (_e *MockLabelRepository_Expecter) Update(ctx interface{}, label interface{}) *MockLabelRepository_Update_Call {
	return &MockLabelRepository_Update_Call{Call: _e.mock.On("Update", ctx, label)}
}

func (_c *MockLabelRepository_Update_Call) Run(run func(ctx context.Context, label *entity.Label)) *MockLabelRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Label
		if args[1] != nil {
			arg1 = args[1].(*entity.Label)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLabelRepository_Update_Call) Return(err error) *MockLabelRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLabelRepository_Update_Call) RunAndReturn(run func(ctx context.Context, label *entity.Label) error) *MockLabelRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
