// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/domain/entity"
)

// NewMockPermissionRepository creates a new instance of MockPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionRepository {
	mock := &MockPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPermissionRepository is an autogenerated mock type for the PermissionRepository type
type MockPermissionRepository struct {
	mock.Mock
}

type MockPermissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionRepository) EXPECT() *MockPermissionRepository_Expecter {
	return &MockPermissionRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockPermissionRepository
func (_mock *MockPermissionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPermissionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPermissionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPermissionRepository_Delete_Call {
	return &MockPermissionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPermissionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPermissionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionRepository_Delete_Call) Return(err error) *MockPermissionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockPermissionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByID provides a mock function for the type MockPermissionRepository
func (_mock *MockPermissionRepository) ExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionRepository_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockPermissionRepository_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPermissionRepository_Expecter) ExistsByID(ctx interface{}, id interface{}) *MockPermissionRepository_ExistsByID_Call {
	return &MockPermissionRepository_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, id)}
}

func (_c *MockPermissionRepository_ExistsByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPermissionRepository_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionRepository_ExistsByID_Call) Return(b bool, err error) *MockPermissionRepository_ExistsByID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPermissionRepository_ExistsByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockPermissionRepository_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockPermissionRepository
func (_mock *MockPermissionRepository) FindAll(ctx context.Context) ([]*entity.Permission, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Permission, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Permission); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPermissionRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPermissionRepository_Expecter) FindAll(ctx interface{}) *MockPermissionRepository_FindAll_Call {
	return &MockPermissionRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockPermissionRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockPermissionRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPermissionRepository_FindAll_Call) Return(permissions []*entity.Permission, err error) *MockPermissionRepository_FindAll_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockPermissionRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Permission, error)) *MockPermissionRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockPermissionRepository
func (_mock *MockPermissionRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Permission, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Permission, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Permission); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPermissionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPermissionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockPermissionRepository_FindByID_Call {
	return &MockPermissionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPermissionRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPermissionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionRepository_FindByID_Call) Return(permission *entity.Permission, err error) *MockPermissionRepository_FindByID_Call {
	_c.Call.Return(permission, err)
	return _c
}

func (_c *MockPermissionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Permission, error)) *MockPermissionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockPermissionRepository
func (_mock *MockPermissionRepository) FindByName(ctx context.Context, name string) (*entity.Permission, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Permission, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Permission); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockPermissionRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPermissionRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockPermissionRepository_FindByName_Call {
	return &MockPermissionRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockPermissionRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockPermissionRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionRepository_FindByName_Call) Return(permission *entity.Permission, err error) *MockPermissionRepository_FindByName_Call {
	_c.Call.Return(permission, err)
	return _c
}

func (_c *MockPermissionRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Permission, error)) *MockPermissionRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRoleID provides a mock function for the type MockPermissionRepository
func (_mock *MockPermissionRepository) FindByRoleID(ctx context.Context, roleID uuid.UUID) ([]*entity.Permission, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoleID")
	}

	var r0 []*entity.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Permission, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Permission); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionRepository_FindByRoleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRoleID'
type MockPermissionRepository_FindByRoleID_Call struct {
	*mock.Call
}

// FindByRoleID is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
func (_e *MockPermissionRepository_Expecter) FindByRoleID(ctx interface{}, roleID interface{}) *MockPermissionRepository_FindByRoleID_Call {
	return &MockPermissionRepository_FindByRoleID_Call{Call: _e.mock.On("FindByRoleID", ctx, roleID)}
}

func (_c *MockPermissionRepository_FindByRoleID_Call) Run(run func(ctx context.Context, roleID uuid.UUID)) *MockPermissionRepository_FindByRoleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionRepository_FindByRoleID_Call) Return(permissions []*entity.Permission, err error) *MockPermissionRepository_FindByRoleID_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockPermissionRepository_FindByRoleID_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID) ([]*entity.Permission, error)) *MockPermissionRepository_FindByRoleID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockPermissionRepository
func (_mock *MockPermissionRepository) Save(ctx context.Context, permission *entity.Permission) error {
	ret := _mock.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Permission) error); ok {
		r0 = returnFunc(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPermissionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPermissionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *entity.Permission
func (_e *MockPermissionRepository_Expecter) Save(ctx interface{}, permission interface{}) *MockPermissionRepository_Save_Call {
	return &MockPermissionRepository_Save_Call{Call: _e.mock.On("Save", ctx, permission)}
}

func (_c *MockPermissionRepository_Save_Call) Run(run func(ctx context.Context, permission *entity.Permission)) *MockPermissionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Permission
		if args[1] != nil {
			arg1 = args[1].(*entity.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPermissionRepository_Save_Call) Return(err error) *MockPermissionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPermissionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, permission *entity.Permission) error) *MockPermissionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
