// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/dto"
)

// NewMockRoleService creates a new instance of MockRoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleService {
	mock := &MockRoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleService is an autogenerated mock type for the RoleService type
type MockRoleService struct {
	mock.Mock
}

type MockRoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleService) EXPECT() *MockRoleService_Expecter {
	return &MockRoleService_Expecter{mock: &_m.Mock}
}

// AddPermission provides a mock function for the type MockRoleService
func (_mock *MockRoleService) AddPermission(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) (*dto.RoleOutput, error) {
	ret := _mock.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for AddPermission")
	}

	var r0 *dto.RoleOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.RoleOutput, error)); ok {
		return returnFunc(ctx, roleID, permissionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.RoleOutput); ok {
		r0 = returnFunc(ctx, roleID, permissionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roleID, permissionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleService_AddPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermission'
type MockRoleService_AddPermission_Call struct {
	*mock.Call
}

// AddPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
func (_e *MockRoleService_Expecter) AddPermission(ctx interface{}, roleID interface{}, permissionID interface{}) *MockRoleService_AddPermission_Call {
	return &MockRoleService_AddPermission_Call{Call: _e.mock.On("AddPermission", ctx, roleID, permissionID)}
}

func (_c *MockRoleService_AddPermission_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID)) *MockRoleService_AddPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleService_AddPermission_Call) Return(roleOutput *dto.RoleOutput, err error) *MockRoleService_AddPermission_Call {
	_c.Call.Return(roleOutput, err)
	return _c
}

func (_c *MockRoleService_AddPermission_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) (*dto.RoleOutput, error)) *MockRoleService_AddPermission_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type MockRoleService
func (_mock *MockRoleService) CreateRole(ctx context.Context, input dto.CreateRoleInput) (*dto.RoleOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *dto.RoleOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateRoleInput) (*dto.RoleOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateRoleInput) *dto.RoleOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateRoleInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleService_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockRoleService_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateRoleInput
func (_e *MockRoleService_Expecter) CreateRole(ctx interface{}, input interface{}) *MockRoleService_CreateRole_Call {
	return &MockRoleService_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, input)}
}

func (_c *MockRoleService_CreateRole_Call) Run(run func(ctx context.Context, input dto.CreateRoleInput)) *MockRoleService_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateRoleInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateRoleInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleService_CreateRole_Call) Return(roleOutput *dto.RoleOutput, err error) *MockRoleService_CreateRole_Call {
	_c.Call.Return(roleOutput, err)
	return _c
}

func (_c *MockRoleService_CreateRole_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateRoleInput) (*dto.RoleOutput, error)) *MockRoleService_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type MockRoleService
func (_mock *MockRoleService) DeleteRole(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleService_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockRoleService_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRoleService_Expecter) DeleteRole(ctx interface{}, id interface{}) *MockRoleService_DeleteRole_Call {
	return &MockRoleService_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, id)}
}

func (_c *MockRoleService_DeleteRole_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRoleService_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleService_DeleteRole_Call) Return(err error) *MockRoleService_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleService_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRoleService_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function for the type MockRoleService
func (_mock *MockRoleService) GetRole(ctx context.Context, id uuid.UUID) (*dto.RoleOutput, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *dto.RoleOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.RoleOutput, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.RoleOutput); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleService_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type MockRoleService_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRoleService_Expecter) GetRole(ctx interface{}, id interface{}) *MockRoleService_GetRole_Call {
	return &MockRoleService_GetRole_Call{Call: _e.mock.On("GetRole", ctx, id)}
}

func (_c *MockRoleService_GetRole_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRoleService_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleService_GetRole_Call) Return(roleOutput *dto.RoleOutput, err error) *MockRoleService_GetRole_Call {
	_c.Call.Return(roleOutput, err)
	return _c
}

func (_c *MockRoleService_GetRole_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*dto.RoleOutput, error)) *MockRoleService_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function for the type MockRoleService
func (_mock *MockRoleService) ListRoles(ctx context.Context) ([]*dto.RoleOutput, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []*dto.RoleOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*dto.RoleOutput, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*dto.RoleOutput); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.RoleOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleService_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockRoleService_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleService_Expecter) ListRoles(ctx interface{}) *MockRoleService_ListRoles_Call {
	return &MockRoleService_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx)}
}

func (_c *MockRoleService_ListRoles_Call) Run(run func(ctx context.Context)) *MockRoleService_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoleService_ListRoles_Call) Return(roleOutputs []*dto.RoleOutput, err error) *MockRoleService_ListRoles_Call {
	_c.Call.Return(roleOutputs, err)
	return _c
}

func (_c *MockRoleService_ListRoles_Call) RunAndReturn(run func(ctx context.Context) ([]*dto.RoleOutput, error)) *MockRoleService_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermission provides a mock function for the type MockRoleService
func (_mock *MockRoleService) RemovePermission(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) (*dto.RoleOutput, error) {
	ret := _mock.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 *dto.RoleOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.RoleOutput, error)); ok {
		return returnFunc(ctx, roleID, permissionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.RoleOutput); ok {
		r0 = returnFunc(ctx, roleID, permissionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roleID, permissionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleService_RemovePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermission'
type MockRoleService_RemovePermission_Call struct {
	*mock.Call
}

// RemovePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
func (_e *MockRoleService_Expecter) RemovePermission(ctx interface{}, roleID interface{}, permissionID interface{}) *MockRoleService_RemovePermission_Call {
	return &MockRoleService_RemovePermission_Call{Call: _e.mock.On("RemovePermission", ctx, roleID, permissionID)}
}

func (_c *MockRoleService_RemovePermission_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID)) *MockRoleService_RemovePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleService_RemovePermission_Call) Return(roleOutput *dto.RoleOutput, err error) *MockRoleService_RemovePermission_Call {
	_c.Call.Return(roleOutput, err)
	return _c
}

func (_c *MockRoleService_RemovePermission_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) (*dto.RoleOutput, error)) *MockRoleService_RemovePermission_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type MockRoleService
func (_mock *MockRoleService) UpdateRole(ctx context.Context, id uuid.UUID, input dto.UpdateRoleInput) (*dto.RoleOutput, error) {
	ret := _mock.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 *dto.RoleOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateRoleInput) (*dto.RoleOutput, error)); ok {
		return returnFunc(ctx, id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateRoleInput) *dto.RoleOutput); ok {
		r0 = returnFunc(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoleOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateRoleInput) error); ok {
		r1 = returnFunc(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleService_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockRoleService_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input dto.UpdateRoleInput
func (_e *MockRoleService_Expecter) UpdateRole(ctx interface{}, id interface{}, input interface{}) *MockRoleService_UpdateRole_Call {
	return &MockRoleService_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, id, input)}
}

func (_c *MockRoleService_UpdateRole_Call) Run(run func(ctx context.Context, id uuid.UUID, input dto.UpdateRoleInput)) *MockRoleService_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.UpdateRoleInput
		if args[2] != nil {
			arg2 = args[2].(dto.UpdateRoleInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleService_UpdateRole_Call) Return(roleOutput *dto.RoleOutput, err error) *MockRoleService_UpdateRole_Call {
	_c.Call.Return(roleOutput, err)
	return _c
}

func (_c *MockRoleService_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, input dto.UpdateRoleInput) (*dto.RoleOutput, error)) *MockRoleService_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
