// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/port/output"
	"github.com/handiism/go-clean-arch-poc/internal/domain/entity"
	"github.com/handiism/go-clean-arch-poc/internal/domain/valueobject"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// CountByStatus provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) CountByStatus(ctx context.Context, status valueobject.TaskStatus) (int64, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TaskStatus) (int64, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TaskStatus) int64); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.TaskStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type MockTaskRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status valueobject.TaskStatus
func (_e *MockTaskRepository_Expecter) CountByStatus(ctx interface{}, status interface{}) *MockTaskRepository_CountByStatus_Call {
	return &MockTaskRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, status)}
}

func (_c *MockTaskRepository_CountByStatus_Call) Run(run func(ctx context.Context, status valueobject.TaskStatus)) *MockTaskRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.TaskStatus
		if args[1] != nil {
			arg1 = args[1].(valueobject.TaskStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_CountByStatus_Call) Return(n int64, err error) *MockTaskRepository_CountByStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTaskRepository_CountByStatus_Call) RunAndReturn(run func(ctx context.Context, status valueobject.TaskStatus) (int64, error)) *MockTaskRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(err error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) ExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockTaskRepository_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskRepository_Expecter) ExistsByID(ctx interface{}, id interface{}) *MockTaskRepository_ExistsByID_Call {
	return &MockTaskRepository_ExistsByID_Call{Call: _e.mock.On("ExistsByID", ctx, id)}
}

func (_c *MockTaskRepository_ExistsByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_ExistsByID_Call) Return(b bool, err error) *MockTaskRepository_ExistsByID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTaskRepository_ExistsByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockTaskRepository_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindAll(ctx context.Context, filter output.TaskFilter, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error) {
	ret := _mock.Called(ctx, filter, pagination)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Task
	var r1 *output.PaginatedResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, output.TaskFilter, output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)); ok {
		return returnFunc(ctx, filter, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, output.TaskFilter, output.Pagination) []*entity.Task); ok {
		r0 = returnFunc(ctx, filter, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, output.TaskFilter, output.Pagination) *output.PaginatedResult); ok {
		r1 = returnFunc(ctx, filter, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*output.PaginatedResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, output.TaskFilter, output.Pagination) error); ok {
		r2 = returnFunc(ctx, filter, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTaskRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockTaskRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter output.TaskFilter
//   - pagination output.Pagination
func (_e *MockTaskRepository_Expecter) FindAll(ctx interface{}, filter interface{}, pagination interface{}) *MockTaskRepository_FindAll_Call {
	return &MockTaskRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter, pagination)}
}

func (_c *MockTaskRepository_FindAll_Call) Run(run func(ctx context.Context, filter output.TaskFilter, pagination output.Pagination)) *MockTaskRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 output.TaskFilter
		if args[1] != nil {
			arg1 = args[1].(output.TaskFilter)
		}
		var arg2 output.Pagination
		if args[2] != nil {
			arg2 = args[2].(output.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindAll_Call) Return(tasks []*entity.Task, paginatedResult *output.PaginatedResult, err error) *MockTaskRepository_FindAll_Call {
	_c.Call.Return(tasks, paginatedResult, err)
	return _c
}

func (_c *MockTaskRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, filter output.TaskFilter, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)) *MockTaskRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAssignee provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindByAssignee(ctx context.Context, assigneeID uuid.UUID, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error) {
	ret := _mock.Called(ctx, assigneeID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for FindByAssignee")
	}

	var r0 []*entity.Task
	var r1 *output.PaginatedResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)); ok {
		return returnFunc(ctx, assigneeID, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, output.Pagination) []*entity.Task); ok {
		r0 = returnFunc(ctx, assigneeID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, output.Pagination) *output.PaginatedResult); ok {
		r1 = returnFunc(ctx, assigneeID, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*output.PaginatedResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, output.Pagination) error); ok {
		r2 = returnFunc(ctx, assigneeID, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTaskRepository_FindByAssignee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAssignee'
type MockTaskRepository_FindByAssignee_Call struct {
	*mock.Call
}

// FindByAssignee is a helper method to define mock.On call
//   - ctx context.Context
//   - assigneeID uuid.UUID
//   - pagination output.Pagination
func (_e *MockTaskRepository_Expecter) FindByAssignee(ctx interface{}, assigneeID interface{}, pagination interface{}) *MockTaskRepository_FindByAssignee_Call {
	return &MockTaskRepository_FindByAssignee_Call{Call: _e.mock.On("FindByAssignee", ctx, assigneeID, pagination)}
}

func (_c *MockTaskRepository_FindByAssignee_Call) Run(run func(ctx context.Context, assigneeID uuid.UUID, pagination output.Pagination)) *MockTaskRepository_FindByAssignee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 output.Pagination
		if args[2] != nil {
			arg2 = args[2].(output.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindByAssignee_Call) Return(tasks []*entity.Task, paginatedResult *output.PaginatedResult, err error) *MockTaskRepository_FindByAssignee_Call {
	_c.Call.Return(tasks, paginatedResult, err)
	return _c
}

func (_c *MockTaskRepository_FindByAssignee_Call) RunAndReturn(run func(ctx context.Context, assigneeID uuid.UUID, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)) *MockTaskRepository_FindByAssignee_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCreator provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindByCreator(ctx context.Context, creatorID uuid.UUID, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error) {
	ret := _mock.Called(ctx, creatorID, pagination)

	if len(ret) == 0 {
		panic("no return value specified for FindByCreator")
	}

	var r0 []*entity.Task
	var r1 *output.PaginatedResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)); ok {
		return returnFunc(ctx, creatorID, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, output.Pagination) []*entity.Task); ok {
		r0 = returnFunc(ctx, creatorID, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, output.Pagination) *output.PaginatedResult); ok {
		r1 = returnFunc(ctx, creatorID, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*output.PaginatedResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, output.Pagination) error); ok {
		r2 = returnFunc(ctx, creatorID, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTaskRepository_FindByCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCreator'
type MockTaskRepository_FindByCreator_Call struct {
	*mock.Call
}

// FindByCreator is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID uuid.UUID
//   - pagination output.Pagination
func (_e *MockTaskRepository_Expecter) FindByCreator(ctx interface{}, creatorID interface{}, pagination interface{}) *MockTaskRepository_FindByCreator_Call {
	return &MockTaskRepository_FindByCreator_Call{Call: _e.mock.On("FindByCreator", ctx, creatorID, pagination)}
}

func (_c *MockTaskRepository_FindByCreator_Call) Run(run func(ctx context.Context, creatorID uuid.UUID, pagination output.Pagination)) *MockTaskRepository_FindByCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 output.Pagination
		if args[2] != nil {
			arg2 = args[2].(output.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindByCreator_Call) Return(tasks []*entity.Task, paginatedResult *output.PaginatedResult, err error) *MockTaskRepository_FindByCreator_Call {
	_c.Call.Return(tasks, paginatedResult, err)
	return _c
}

func (_c *MockTaskRepository_FindByCreator_Call) RunAndReturn(run func(ctx context.Context, creatorID uuid.UUID, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)) *MockTaskRepository_FindByCreator_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTaskRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTaskRepository_FindByID_Call {
	return &MockTaskRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTaskRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindByID_Call) Return(task *entity.Task, err error) *MockTaskRepository_FindByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Task, error)) *MockTaskRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOverdue provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindOverdue(ctx context.Context, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error) {
	ret := _mock.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for FindOverdue")
	}

	var r0 []*entity.Task
	var r1 *output.PaginatedResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)); ok {
		return returnFunc(ctx, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, output.Pagination) []*entity.Task); ok {
		r0 = returnFunc(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, output.Pagination) *output.PaginatedResult); ok {
		r1 = returnFunc(ctx, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*output.PaginatedResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, output.Pagination) error); ok {
		r2 = returnFunc(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTaskRepository_FindOverdue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOverdue'
type MockTaskRepository_FindOverdue_Call struct {
	*mock.Call
}

// FindOverdue is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination output.Pagination
func (_e *MockTaskRepository_Expecter) FindOverdue(ctx interface{}, pagination interface{}) *MockTaskRepository_FindOverdue_Call {
	return &MockTaskRepository_FindOverdue_Call{Call: _e.mock.On("FindOverdue", ctx, pagination)}
}

func (_c *MockTaskRepository_FindOverdue_Call) Run(run func(ctx context.Context, pagination output.Pagination)) *MockTaskRepository_FindOverdue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 output.Pagination
		if args[1] != nil {
			arg1 = args[1].(output.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindOverdue_Call) Return(tasks []*entity.Task, paginatedResult *output.PaginatedResult, err error) *MockTaskRepository_FindOverdue_Call {
	_c.Call.Return(tasks, paginatedResult, err)
	return _c
}

func (_c *MockTaskRepository_FindOverdue_Call) RunAndReturn(run func(ctx context.Context, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)) *MockTaskRepository_FindOverdue_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Save(ctx context.Context, task *entity.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTaskRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - task *entity.Task
func (_e *MockTaskRepository_Expecter) Save(ctx interface{}, task interface{}) *MockTaskRepository_Save_Call {
	return &MockTaskRepository_Save_Call{Call: _e.mock.On("Save", ctx, task)}
}

func (_c *MockTaskRepository_Save_Call) Run(run func(ctx context.Context, task *entity.Task)) *MockTaskRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Task
		if args[1] != nil {
			arg1 = args[1].(*entity.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Save_Call) Return(err error) *MockTaskRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Save_Call) RunAndReturn(run func(ctx context.Context, task *entity.Task) error) *MockTaskRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Search(ctx context.Context, query string, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error) {
	ret := _mock.Called(ctx, query, pagination)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entity.Task
	var r1 *output.PaginatedResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)); ok {
		return returnFunc(ctx, query, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, output.Pagination) []*entity.Task); ok {
		r0 = returnFunc(ctx, query, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, output.Pagination) *output.PaginatedResult); ok {
		r1 = returnFunc(ctx, query, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*output.PaginatedResult)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, output.Pagination) error); ok {
		r2 = returnFunc(ctx, query, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTaskRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockTaskRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - pagination output.Pagination
func (_e *MockTaskRepository_Expecter) Search(ctx interface{}, query interface{}, pagination interface{}) *MockTaskRepository_Search_Call {
	return &MockTaskRepository_Search_Call{Call: _e.mock.On("Search", ctx, query, pagination)}
}

func (_c *MockTaskRepository_Search_Call) Run(run func(ctx context.Context, query string, pagination output.Pagination)) *MockTaskRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 output.Pagination
		if args[2] != nil {
			arg2 = args[2].(output.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Search_Call) Return(tasks []*entity.Task, paginatedResult *output.PaginatedResult, err error) *MockTaskRepository_Search_Call {
	_c.Call.Return(tasks, paginatedResult, err)
	return _c
}

func (_c *MockTaskRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query string, pagination output.Pagination) ([]*entity.Task, *output.PaginatedResult, error)) *MockTaskRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Update(ctx context.Context, task *entity.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task *entity.Task
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, task interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, task *entity.Task)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Task
		if args[1] != nil {
			arg1 = args[1].(*entity.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(err error) *MockTaskRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(ctx context.Context, task *entity.Task) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
