// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/domain/entity"
)

// NewMockTaskAttachmentRepository creates a new instance of MockTaskAttachmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskAttachmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskAttachmentRepository {
	mock := &MockTaskAttachmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskAttachmentRepository is an autogenerated mock type for the TaskAttachmentRepository type
type MockTaskAttachmentRepository struct {
	mock.Mock
}

type MockTaskAttachmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskAttachmentRepository) EXPECT() *MockTaskAttachmentRepository_Expecter {
	return &MockTaskAttachmentRepository_Expecter{mock: &_m.Mock}
}

// DeleteAttachment provides a mock function for the type MockTaskAttachmentRepository
func (_mock *MockTaskAttachmentRepository) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskAttachmentRepository_DeleteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachment'
type MockTaskAttachmentRepository_DeleteAttachment_Call struct {
	*mock.Call
}

// DeleteAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskAttachmentRepository_Expecter) DeleteAttachment(ctx interface{}, id interface{}) *MockTaskAttachmentRepository_DeleteAttachment_Call {
	return &MockTaskAttachmentRepository_DeleteAttachment_Call{Call: _e.mock.On("DeleteAttachment", ctx, id)}
}

func (_c *MockTaskAttachmentRepository_DeleteAttachment_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskAttachmentRepository_DeleteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskAttachmentRepository_DeleteAttachment_Call) Return(err error) *MockTaskAttachmentRepository_DeleteAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskAttachmentRepository_DeleteAttachment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTaskAttachmentRepository_DeleteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttachmentsByTaskID provides a mock function for the type MockTaskAttachmentRepository
func (_mock *MockTaskAttachmentRepository) DeleteAttachmentsByTaskID(ctx context.Context, taskID uuid.UUID) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachmentsByTaskID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachmentsByTaskID'
type MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call struct {
	*mock.Call
}

// DeleteAttachmentsByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
func (_e *MockTaskAttachmentRepository_Expecter) DeleteAttachmentsByTaskID(ctx interface{}, taskID interface{}) *MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call {
	return &MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call{Call: _e.mock.On("DeleteAttachmentsByTaskID", ctx, taskID)}
}

func (_c *MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call) Return(err error) *MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) error) *MockTaskAttachmentRepository_DeleteAttachmentsByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAttachmentByID provides a mock function for the type MockTaskAttachmentRepository
func (_mock *MockTaskAttachmentRepository) FindAttachmentByID(ctx context.Context, id uuid.UUID) (*entity.TaskAttachment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindAttachmentByID")
	}

	var r0 *entity.TaskAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.TaskAttachment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.TaskAttachment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskAttachmentRepository_FindAttachmentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAttachmentByID'
type MockTaskAttachmentRepository_FindAttachmentByID_Call struct {
	*mock.Call
}

// FindAttachmentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskAttachmentRepository_Expecter) FindAttachmentByID(ctx interface{}, id interface{}) *MockTaskAttachmentRepository_FindAttachmentByID_Call {
	return &MockTaskAttachmentRepository_FindAttachmentByID_Call{Call: _e.mock.On("FindAttachmentByID", ctx, id)}
}

func (_c *MockTaskAttachmentRepository_FindAttachmentByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskAttachmentRepository_FindAttachmentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskAttachmentRepository_FindAttachmentByID_Call) Return(taskAttachment *entity.TaskAttachment, err error) *MockTaskAttachmentRepository_FindAttachmentByID_Call {
	_c.Call.Return(taskAttachment, err)
	return _c
}

func (_c *MockTaskAttachmentRepository_FindAttachmentByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.TaskAttachment, error)) *MockTaskAttachmentRepository_FindAttachmentByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAttachmentsByTaskID provides a mock function for the type MockTaskAttachmentRepository
func (_mock *MockTaskAttachmentRepository) FindAttachmentsByTaskID(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskAttachment, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for FindAttachmentsByTaskID")
	}

	var r0 []*entity.TaskAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TaskAttachment, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TaskAttachment); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAttachmentsByTaskID'
type MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call struct {
	*mock.Call
}

// FindAttachmentsByTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
func (_e *MockTaskAttachmentRepository_Expecter) FindAttachmentsByTaskID(ctx interface{}, taskID interface{}) *MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call {
	return &MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call{Call: _e.mock.On("FindAttachmentsByTaskID", ctx, taskID)}
}

func (_c *MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call) Return(taskAttachments []*entity.TaskAttachment, err error) *MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call {
	_c.Call.Return(taskAttachments, err)
	return _c
}

func (_c *MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskAttachment, error)) *MockTaskAttachmentRepository_FindAttachmentsByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAttachment provides a mock function for the type MockTaskAttachmentRepository
func (_mock *MockTaskAttachmentRepository) SaveAttachment(ctx context.Context, attachment *entity.TaskAttachment) error {
	ret := _mock.Called(ctx, attachment)

	if len(ret) == 0 {
		panic("no return value specified for SaveAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TaskAttachment) error); ok {
		r0 = returnFunc(ctx, attachment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskAttachmentRepository_SaveAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAttachment'
type MockTaskAttachmentRepository_SaveAttachment_Call struct {
	*mock.Call
}

// SaveAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - attachment *entity.TaskAttachment
func (_e *MockTaskAttachmentRepository_Expecter) SaveAttachment(ctx interface{}, attachment interface{}) *MockTaskAttachmentRepository_SaveAttachment_Call {
	return &MockTaskAttachmentRepository_SaveAttachment_Call{Call: _e.mock.On("SaveAttachment", ctx, attachment)}
}

func (_c *MockTaskAttachmentRepository_SaveAttachment_Call) Run(run func(ctx context.Context, attachment *entity.TaskAttachment)) *MockTaskAttachmentRepository_SaveAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.TaskAttachment
		if args[1] != nil {
			arg1 = args[1].(*entity.TaskAttachment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskAttachmentRepository_SaveAttachment_Call) Return(err error) *MockTaskAttachmentRepository_SaveAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskAttachmentRepository_SaveAttachment_Call) RunAndReturn(run func(ctx context.Context, attachment *entity.TaskAttachment) error) *MockTaskAttachmentRepository_SaveAttachment_Call {
	_c.Call.Return(run)
	return _c
}
