// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/dto"
)

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// AddLabel provides a mock function for the type MockTaskService
func (_mock *MockTaskService) AddLabel(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, taskID, labelID)

	if len(ret) == 0 {
		panic("no return value specified for AddLabel")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, taskID, labelID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, taskID, labelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID, labelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_AddLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLabel'
type MockTaskService_AddLabel_Call struct {
	*mock.Call
}

// AddLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - labelID uuid.UUID
func (_e *MockTaskService_Expecter) AddLabel(ctx interface{}, taskID interface{}, labelID interface{}) *MockTaskService_AddLabel_Call {
	return &MockTaskService_AddLabel_Call{Call: _e.mock.On("AddLabel", ctx, taskID, labelID)}
}

func (_c *MockTaskService_AddLabel_Call) Run(run func(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID)) *MockTaskService_AddLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_AddLabel_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_AddLabel_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_AddLabel_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID) (*dto.TaskOutput, error)) *MockTaskService_AddLabel_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) ArchiveTask(ctx context.Context, taskID uuid.UUID) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveTask")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_ArchiveTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveTask'
type MockTaskService_ArchiveTask_Call struct {
	*mock.Call
}

// ArchiveTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
func (_e *MockTaskService_Expecter) ArchiveTask(ctx interface{}, taskID interface{}) *MockTaskService_ArchiveTask_Call {
	return &MockTaskService_ArchiveTask_Call{Call: _e.mock.On("ArchiveTask", ctx, taskID)}
}

func (_c *MockTaskService_ArchiveTask_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskService_ArchiveTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_ArchiveTask_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_ArchiveTask_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_ArchiveTask_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) (*dto.TaskOutput, error)) *MockTaskService_ArchiveTask_Call {
	_c.Call.Return(run)
	return _c
}

// AssignTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) AssignTask(ctx context.Context, taskID uuid.UUID, assigneeID uuid.UUID) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, taskID, assigneeID)

	if len(ret) == 0 {
		panic("no return value specified for AssignTask")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, taskID, assigneeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, taskID, assigneeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID, assigneeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_AssignTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignTask'
type MockTaskService_AssignTask_Call struct {
	*mock.Call
}

// AssignTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - assigneeID uuid.UUID
func (_e *MockTaskService_Expecter) AssignTask(ctx interface{}, taskID interface{}, assigneeID interface{}) *MockTaskService_AssignTask_Call {
	return &MockTaskService_AssignTask_Call{Call: _e.mock.On("AssignTask", ctx, taskID, assigneeID)}
}

func (_c *MockTaskService_AssignTask_Call) Run(run func(ctx context.Context, taskID uuid.UUID, assigneeID uuid.UUID)) *MockTaskService_AssignTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_AssignTask_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_AssignTask_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_AssignTask_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, assigneeID uuid.UUID) (*dto.TaskOutput, error)) *MockTaskService_AssignTask_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeTaskStatus provides a mock function for the type MockTaskService
func (_mock *MockTaskService) ChangeTaskStatus(ctx context.Context, taskID uuid.UUID, status string) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, taskID, status)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTaskStatus")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, taskID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, taskID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, taskID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_ChangeTaskStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeTaskStatus'
type MockTaskService_ChangeTaskStatus_Call struct {
	*mock.Call
}

// ChangeTaskStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - status string
func (_e *MockTaskService_Expecter) ChangeTaskStatus(ctx interface{}, taskID interface{}, status interface{}) *MockTaskService_ChangeTaskStatus_Call {
	return &MockTaskService_ChangeTaskStatus_Call{Call: _e.mock.On("ChangeTaskStatus", ctx, taskID, status)}
}

func (_c *MockTaskService_ChangeTaskStatus_Call) Run(run func(ctx context.Context, taskID uuid.UUID, status string)) *MockTaskService_ChangeTaskStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_ChangeTaskStatus_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_ChangeTaskStatus_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_ChangeTaskStatus_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, status string) (*dto.TaskOutput, error)) *MockTaskService_ChangeTaskStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) CompleteTask(ctx context.Context, taskID uuid.UUID) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_CompleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTask'
type MockTaskService_CompleteTask_Call struct {
	*mock.Call
}

// CompleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
func (_e *MockTaskService_Expecter) CompleteTask(ctx interface{}, taskID interface{}) *MockTaskService_CompleteTask_Call {
	return &MockTaskService_CompleteTask_Call{Call: _e.mock.On("CompleteTask", ctx, taskID)}
}

func (_c *MockTaskService_CompleteTask_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskService_CompleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_CompleteTask_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_CompleteTask_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_CompleteTask_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) (*dto.TaskOutput, error)) *MockTaskService_CompleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) CreateTask(ctx context.Context, input dto.CreateTaskInput) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateTaskInput) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateTaskInput) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateTaskInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateTaskInput
func (_e *MockTaskService_Expecter) CreateTask(ctx interface{}, input interface{}) *MockTaskService_CreateTask_Call {
	return &MockTaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, input)}
}

func (_c *MockTaskService_CreateTask_Call) Run(run func(ctx context.Context, input dto.CreateTaskInput)) *MockTaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateTaskInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateTaskInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_CreateTask_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_CreateTask_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateTaskInput) (*dto.TaskOutput, error)) *MockTaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) DeleteTask(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskService_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskService_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskService_Expecter) DeleteTask(ctx interface{}, id interface{}) *MockTaskService_DeleteTask_Call {
	return &MockTaskService_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, id)}
}

func (_c *MockTaskService_DeleteTask_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskService_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_DeleteTask_Call) Return(err error) *MockTaskService_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskService_DeleteTask_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTaskService_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskAttachment provides a mock function for the type MockTaskService
func (_mock *MockTaskService) DeleteTaskAttachment(ctx context.Context, taskID uuid.UUID, attachmentID uuid.UUID) error {
	ret := _mock.Called(ctx, taskID, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, taskID, attachmentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskService_DeleteTaskAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskAttachment'
type MockTaskService_DeleteTaskAttachment_Call struct {
	*mock.Call
}

// DeleteTaskAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - attachmentID uuid.UUID
func (_e *MockTaskService_Expecter) DeleteTaskAttachment(ctx interface{}, taskID interface{}, attachmentID interface{}) *MockTaskService_DeleteTaskAttachment_Call {
	return &MockTaskService_DeleteTaskAttachment_Call{Call: _e.mock.On("DeleteTaskAttachment", ctx, taskID, attachmentID)}
}

func (_c *MockTaskService_DeleteTaskAttachment_Call) Run(run func(ctx context.Context, taskID uuid.UUID, attachmentID uuid.UUID)) *MockTaskService_DeleteTaskAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_DeleteTaskAttachment_Call) Return(err error) *MockTaskService_DeleteTaskAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskService_DeleteTaskAttachment_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, attachmentID uuid.UUID) error) *MockTaskService_DeleteTaskAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadTaskAttachment provides a mock function for the type MockTaskService
func (_mock *MockTaskService) DownloadTaskAttachment(ctx context.Context, taskID uuid.UUID, attachmentID uuid.UUID) (io.ReadCloser, *dto.TaskAttachmentOutput, error) {
	ret := _mock.Called(ctx, taskID, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadTaskAttachment")
	}

	var r0 io.ReadCloser
	var r1 *dto.TaskAttachmentOutput
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (io.ReadCloser, *dto.TaskAttachmentOutput, error)); ok {
		return returnFunc(ctx, taskID, attachmentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) io.ReadCloser); ok {
		r0 = returnFunc(ctx, taskID, attachmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) *dto.TaskAttachmentOutput); ok {
		r1 = returnFunc(ctx, taskID, attachmentID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.TaskAttachmentOutput)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, taskID, attachmentID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTaskService_DownloadTaskAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadTaskAttachment'
type MockTaskService_DownloadTaskAttachment_Call struct {
	*mock.Call
}

// DownloadTaskAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - attachmentID uuid.UUID
func (_e *MockTaskService_Expecter) DownloadTaskAttachment(ctx interface{}, taskID interface{}, attachmentID interface{}) *MockTaskService_DownloadTaskAttachment_Call {
	return &MockTaskService_DownloadTaskAttachment_Call{Call: _e.mock.On("DownloadTaskAttachment", ctx, taskID, attachmentID)}
}

func (_c *MockTaskService_DownloadTaskAttachment_Call) Run(run func(ctx context.Context, taskID uuid.UUID, attachmentID uuid.UUID)) *MockTaskService_DownloadTaskAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_DownloadTaskAttachment_Call) Return(readCloser io.ReadCloser, taskAttachmentOutput *dto.TaskAttachmentOutput, err error) *MockTaskService_DownloadTaskAttachment_Call {
	_c.Call.Return(readCloser, taskAttachmentOutput, err)
	return _c
}

func (_c *MockTaskService_DownloadTaskAttachment_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, attachmentID uuid.UUID) (io.ReadCloser, *dto.TaskAttachmentOutput, error)) *MockTaskService_DownloadTaskAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverdueTasks provides a mock function for the type MockTaskService
func (_mock *MockTaskService) GetOverdueTasks(ctx context.Context, pagination dto.Pagination) (*dto.TaskListOutput, error) {
	ret := _mock.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetOverdueTasks")
	}

	var r0 *dto.TaskListOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.Pagination) (*dto.TaskListOutput, error)); ok {
		return returnFunc(ctx, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.Pagination) *dto.TaskListOutput); ok {
		r0 = returnFunc(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskListOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.Pagination) error); ok {
		r1 = returnFunc(ctx, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_GetOverdueTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverdueTasks'
type MockTaskService_GetOverdueTasks_Call struct {
	*mock.Call
}

// GetOverdueTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination dto.Pagination
func (_e *MockTaskService_Expecter) GetOverdueTasks(ctx interface{}, pagination interface{}) *MockTaskService_GetOverdueTasks_Call {
	return &MockTaskService_GetOverdueTasks_Call{Call: _e.mock.On("GetOverdueTasks", ctx, pagination)}
}

func (_c *MockTaskService_GetOverdueTasks_Call) Run(run func(ctx context.Context, pagination dto.Pagination)) *MockTaskService_GetOverdueTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.Pagination
		if args[1] != nil {
			arg1 = args[1].(dto.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_GetOverdueTasks_Call) Return(taskListOutput *dto.TaskListOutput, err error) *MockTaskService_GetOverdueTasks_Call {
	_c.Call.Return(taskListOutput, err)
	return _c
}

func (_c *MockTaskService_GetOverdueTasks_Call) RunAndReturn(run func(ctx context.Context, pagination dto.Pagination) (*dto.TaskListOutput, error)) *MockTaskService_GetOverdueTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) GetTask(ctx context.Context, id uuid.UUID) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskService_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTaskService_Expecter) GetTask(ctx interface{}, id interface{}) *MockTaskService_GetTask_Call {
	return &MockTaskService_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockTaskService_GetTask_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskService_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_GetTask_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_GetTask_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_GetTask_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*dto.TaskOutput, error)) *MockTaskService_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskAttachments provides a mock function for the type MockTaskService
func (_mock *MockTaskService) ListTaskAttachments(ctx context.Context, taskID uuid.UUID) (*dto.TaskAttachmentListOutput, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskAttachments")
	}

	var r0 *dto.TaskAttachmentListOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.TaskAttachmentListOutput, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.TaskAttachmentListOutput); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskAttachmentListOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_ListTaskAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskAttachments'
type MockTaskService_ListTaskAttachments_Call struct {
	*mock.Call
}

// ListTaskAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
func (_e *MockTaskService_Expecter) ListTaskAttachments(ctx interface{}, taskID interface{}) *MockTaskService_ListTaskAttachments_Call {
	return &MockTaskService_ListTaskAttachments_Call{Call: _e.mock.On("ListTaskAttachments", ctx, taskID)}
}

func (_c *MockTaskService_ListTaskAttachments_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskService_ListTaskAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_ListTaskAttachments_Call) Return(taskAttachmentListOutput *dto.TaskAttachmentListOutput, err error) *MockTaskService_ListTaskAttachments_Call {
	_c.Call.Return(taskAttachmentListOutput, err)
	return _c
}

func (_c *MockTaskService_ListTaskAttachments_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) (*dto.TaskAttachmentListOutput, error)) *MockTaskService_ListTaskAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockTaskService
func (_mock *MockTaskService) ListTasks(ctx context.Context, filter dto.TaskFilter, pagination dto.Pagination) (*dto.TaskListOutput, error) {
	ret := _mock.Called(ctx, filter, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 *dto.TaskListOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.TaskFilter, dto.Pagination) (*dto.TaskListOutput, error)); ok {
		return returnFunc(ctx, filter, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.TaskFilter, dto.Pagination) *dto.TaskListOutput); ok {
		r0 = returnFunc(ctx, filter, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskListOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.TaskFilter, dto.Pagination) error); ok {
		r1 = returnFunc(ctx, filter, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskService_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dto.TaskFilter
//   - pagination dto.Pagination
func (_e *MockTaskService_Expecter) ListTasks(ctx interface{}, filter interface{}, pagination interface{}) *MockTaskService_ListTasks_Call {
	return &MockTaskService_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, filter, pagination)}
}

func (_c *MockTaskService_ListTasks_Call) Run(run func(ctx context.Context, filter dto.TaskFilter, pagination dto.Pagination)) *MockTaskService_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.TaskFilter
		if args[1] != nil {
			arg1 = args[1].(dto.TaskFilter)
		}
		var arg2 dto.Pagination
		if args[2] != nil {
			arg2 = args[2].(dto.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_ListTasks_Call) Return(taskListOutput *dto.TaskListOutput, err error) *MockTaskService_ListTasks_Call {
	_c.Call.Return(taskListOutput, err)
	return _c
}

func (_c *MockTaskService_ListTasks_Call) RunAndReturn(run func(ctx context.Context, filter dto.TaskFilter, pagination dto.Pagination) (*dto.TaskListOutput, error)) *MockTaskService_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveLabel provides a mock function for the type MockTaskService
func (_mock *MockTaskService) RemoveLabel(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, taskID, labelID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLabel")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, taskID, labelID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, taskID, labelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID, labelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_RemoveLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveLabel'
type MockTaskService_RemoveLabel_Call struct {
	*mock.Call
}

// RemoveLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - labelID uuid.UUID
func (_e *MockTaskService_Expecter) RemoveLabel(ctx interface{}, taskID interface{}, labelID interface{}) *MockTaskService_RemoveLabel_Call {
	return &MockTaskService_RemoveLabel_Call{Call: _e.mock.On("RemoveLabel", ctx, taskID, labelID)}
}

func (_c *MockTaskService_RemoveLabel_Call) Run(run func(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID)) *MockTaskService_RemoveLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_RemoveLabel_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_RemoveLabel_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_RemoveLabel_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID) (*dto.TaskOutput, error)) *MockTaskService_RemoveLabel_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTasks provides a mock function for the type MockTaskService
func (_mock *MockTaskService) SearchTasks(ctx context.Context, query string, pagination dto.Pagination) (*dto.TaskListOutput, error) {
	ret := _mock.Called(ctx, query, pagination)

	if len(ret) == 0 {
		panic("no return value specified for SearchTasks")
	}

	var r0 *dto.TaskListOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.Pagination) (*dto.TaskListOutput, error)); ok {
		return returnFunc(ctx, query, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.Pagination) *dto.TaskListOutput); ok {
		r0 = returnFunc(ctx, query, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskListOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dto.Pagination) error); ok {
		r1 = returnFunc(ctx, query, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_SearchTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTasks'
type MockTaskService_SearchTasks_Call struct {
	*mock.Call
}

// SearchTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - pagination dto.Pagination
func (_e *MockTaskService_Expecter) SearchTasks(ctx interface{}, query interface{}, pagination interface{}) *MockTaskService_SearchTasks_Call {
	return &MockTaskService_SearchTasks_Call{Call: _e.mock.On("SearchTasks", ctx, query, pagination)}
}

func (_c *MockTaskService_SearchTasks_Call) Run(run func(ctx context.Context, query string, pagination dto.Pagination)) *MockTaskService_SearchTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.Pagination
		if args[2] != nil {
			arg2 = args[2].(dto.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_SearchTasks_Call) Return(taskListOutput *dto.TaskListOutput, err error) *MockTaskService_SearchTasks_Call {
	_c.Call.Return(taskListOutput, err)
	return _c
}

func (_c *MockTaskService_SearchTasks_Call) RunAndReturn(run func(ctx context.Context, query string, pagination dto.Pagination) (*dto.TaskListOutput, error)) *MockTaskService_SearchTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UnassignTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) UnassignTask(ctx context.Context, taskID uuid.UUID) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for UnassignTask")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_UnassignTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnassignTask'
type MockTaskService_UnassignTask_Call struct {
	*mock.Call
}

// UnassignTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
func (_e *MockTaskService_Expecter) UnassignTask(ctx interface{}, taskID interface{}) *MockTaskService_UnassignTask_Call {
	return &MockTaskService_UnassignTask_Call{Call: _e.mock.On("UnassignTask", ctx, taskID)}
}

func (_c *MockTaskService_UnassignTask_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskService_UnassignTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_UnassignTask_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_UnassignTask_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_UnassignTask_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) (*dto.TaskOutput, error)) *MockTaskService_UnassignTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) UpdateTask(ctx context.Context, id uuid.UUID, input dto.UpdateTaskInput) (*dto.TaskOutput, error) {
	ret := _mock.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *dto.TaskOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateTaskInput) (*dto.TaskOutput, error)); ok {
		return returnFunc(ctx, id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateTaskInput) *dto.TaskOutput); ok {
		r0 = returnFunc(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateTaskInput) error); ok {
		r1 = returnFunc(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input dto.UpdateTaskInput
func (_e *MockTaskService_Expecter) UpdateTask(ctx interface{}, id interface{}, input interface{}) *MockTaskService_UpdateTask_Call {
	return &MockTaskService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, id, input)}
}

func (_c *MockTaskService_UpdateTask_Call) Run(run func(ctx context.Context, id uuid.UUID, input dto.UpdateTaskInput)) *MockTaskService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.UpdateTaskInput
		if args[2] != nil {
			arg2 = args[2].(dto.UpdateTaskInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) Return(taskOutput *dto.TaskOutput, err error) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(taskOutput, err)
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, input dto.UpdateTaskInput) (*dto.TaskOutput, error)) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// UploadTaskAttachment provides a mock function for the type MockTaskService
func (_mock *MockTaskService) UploadTaskAttachment(ctx context.Context, taskID uuid.UUID, filename string, contentType string, reader io.Reader) (*dto.TaskAttachmentOutput, error) {
	ret := _mock.Called(ctx, taskID, filename, contentType, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadTaskAttachment")
	}

	var r0 *dto.TaskAttachmentOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, io.Reader) (*dto.TaskAttachmentOutput, error)); ok {
		return returnFunc(ctx, taskID, filename, contentType, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, io.Reader) *dto.TaskAttachmentOutput); ok {
		r0 = returnFunc(ctx, taskID, filename, contentType, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskAttachmentOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, io.Reader) error); ok {
		r1 = returnFunc(ctx, taskID, filename, contentType, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_UploadTaskAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadTaskAttachment'
type MockTaskService_UploadTaskAttachment_Call struct {
	*mock.Call
}

// UploadTaskAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uuid.UUID
//   - filename string
//   - contentType string
//   - reader io.Reader
func (_e *MockTaskService_Expecter) UploadTaskAttachment(ctx interface{}, taskID interface{}, filename interface{}, contentType interface{}, reader interface{}) *MockTaskService_UploadTaskAttachment_Call {
	return &MockTaskService_UploadTaskAttachment_Call{Call: _e.mock.On("UploadTaskAttachment", ctx, taskID, filename, contentType, reader)}
}

func (_c *MockTaskService_UploadTaskAttachment_Call) Run(run func(ctx context.Context, taskID uuid.UUID, filename string, contentType string, reader io.Reader)) *MockTaskService_UploadTaskAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 io.Reader
		if args[4] != nil {
			arg4 = args[4].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTaskService_UploadTaskAttachment_Call) Return(taskAttachmentOutput *dto.TaskAttachmentOutput, err error) *MockTaskService_UploadTaskAttachment_Call {
	_c.Call.Return(taskAttachmentOutput, err)
	return _c
}

func (_c *MockTaskService_UploadTaskAttachment_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, filename string, contentType string, reader io.Reader) (*dto.TaskAttachmentOutput, error)) *MockTaskService_UploadTaskAttachment_Call {
	_c.Call.Return(run)
	return _c
}
