// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/port/output"
)

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// ACLRepository provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) ACLRepository() output.ACLRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ACLRepository")
	}

	var r0 output.ACLRepository
	if returnFunc, ok := ret.Get(0).(func() output.ACLRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(output.ACLRepository)
		}
	}
	return r0
}

// MockUnitOfWork_ACLRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ACLRepository'
type MockUnitOfWork_ACLRepository_Call struct {
	*mock.Call
}

// ACLRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) ACLRepository() *MockUnitOfWork_ACLRepository_Call {
	return &MockUnitOfWork_ACLRepository_Call{Call: _e.mock.On("ACLRepository")}
}

func (_c *MockUnitOfWork_ACLRepository_Call) Run(run func()) *MockUnitOfWork_ACLRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_ACLRepository_Call) Return(aCLRepository output.ACLRepository) *MockUnitOfWork_ACLRepository_Call {
	_c.Call.Return(aCLRepository)
	return _c
}

func (_c *MockUnitOfWork_ACLRepository_Call) RunAndReturn(run func() output.ACLRepository) *MockUnitOfWork_ACLRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Begin(ctx context.Context) (output.UnitOfWork, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 output.UnitOfWork
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (output.UnitOfWork, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) output.UnitOfWork); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(output.UnitOfWork)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUnitOfWork_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockUnitOfWork_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Begin(ctx interface{}) *MockUnitOfWork_Begin_Call {
	return &MockUnitOfWork_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockUnitOfWork_Begin_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Begin_Call) Return(unitOfWork output.UnitOfWork, err error) *MockUnitOfWork_Begin_Call {
	_c.Call.Return(unitOfWork, err)
	return _c
}

func (_c *MockUnitOfWork_Begin_Call) RunAndReturn(run func(ctx context.Context) (output.UnitOfWork, error)) *MockUnitOfWork_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockUnitOfWork_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Commit(ctx interface{}) *MockUnitOfWork_Commit_Call {
	return &MockUnitOfWork_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockUnitOfWork_Commit_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) Return(err error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// LabelRepository provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) LabelRepository() output.LabelRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LabelRepository")
	}

	var r0 output.LabelRepository
	if returnFunc, ok := ret.Get(0).(func() output.LabelRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(output.LabelRepository)
		}
	}
	return r0
}

// MockUnitOfWork_LabelRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LabelRepository'
type MockUnitOfWork_LabelRepository_Call struct {
	*mock.Call
}

// LabelRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) LabelRepository() *MockUnitOfWork_LabelRepository_Call {
	return &MockUnitOfWork_LabelRepository_Call{Call: _e.mock.On("LabelRepository")}
}

func (_c *MockUnitOfWork_LabelRepository_Call) Run(run func()) *MockUnitOfWork_LabelRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_LabelRepository_Call) Return(labelRepository output.LabelRepository) *MockUnitOfWork_LabelRepository_Call {
	_c.Call.Return(labelRepository)
	return _c
}

func (_c *MockUnitOfWork_LabelRepository_Call) RunAndReturn(run func() output.LabelRepository) *MockUnitOfWork_LabelRepository_Call {
	_c.Call.Return(run)
	return _c
}

// PermissionRepository provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) PermissionRepository() output.PermissionRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PermissionRepository")
	}

	var r0 output.PermissionRepository
	if returnFunc, ok := ret.Get(0).(func() output.PermissionRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(output.PermissionRepository)
		}
	}
	return r0
}

// MockUnitOfWork_PermissionRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PermissionRepository'
type MockUnitOfWork_PermissionRepository_Call struct {
	*mock.Call
}

// PermissionRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) PermissionRepository() *MockUnitOfWork_PermissionRepository_Call {
	return &MockUnitOfWork_PermissionRepository_Call{Call: _e.mock.On("PermissionRepository")}
}

func (_c *MockUnitOfWork_PermissionRepository_Call) Run(run func()) *MockUnitOfWork_PermissionRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_PermissionRepository_Call) Return(permissionRepository output.PermissionRepository) *MockUnitOfWork_PermissionRepository_Call {
	_c.Call.Return(permissionRepository)
	return _c
}

func (_c *MockUnitOfWork_PermissionRepository_Call) RunAndReturn(run func() output.PermissionRepository) *MockUnitOfWork_PermissionRepository_Call {
	_c.Call.Return(run)
	return _c
}

// RoleRepository provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) RoleRepository() output.RoleRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RoleRepository")
	}

	var r0 output.RoleRepository
	if returnFunc, ok := ret.Get(0).(func() output.RoleRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(output.RoleRepository)
		}
	}
	return r0
}

// MockUnitOfWork_RoleRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleRepository'
type MockUnitOfWork_RoleRepository_Call struct {
	*mock.Call
}

// RoleRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) RoleRepository() *MockUnitOfWork_RoleRepository_Call {
	return &MockUnitOfWork_RoleRepository_Call{Call: _e.mock.On("RoleRepository")}
}

func (_c *MockUnitOfWork_RoleRepository_Call) Run(run func()) *MockUnitOfWork_RoleRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_RoleRepository_Call) Return(roleRepository output.RoleRepository) *MockUnitOfWork_RoleRepository_Call {
	_c.Call.Return(roleRepository)
	return _c
}

func (_c *MockUnitOfWork_RoleRepository_Call) RunAndReturn(run func() output.RoleRepository) *MockUnitOfWork_RoleRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Rollback(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Rollback(ctx interface{}) *MockUnitOfWork_Rollback_Call {
	return &MockUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) Return(err error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) RunAndReturn(run func(ctx context.Context) error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// TaskRepository provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) TaskRepository() output.TaskRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TaskRepository")
	}

	var r0 output.TaskRepository
	if returnFunc, ok := ret.Get(0).(func() output.TaskRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(output.TaskRepository)
		}
	}
	return r0
}

// MockUnitOfWork_TaskRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TaskRepository'
type MockUnitOfWork_TaskRepository_Call struct {
	*mock.Call
}

// TaskRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) TaskRepository() *MockUnitOfWork_TaskRepository_Call {
	return &MockUnitOfWork_TaskRepository_Call{Call: _e.mock.On("TaskRepository")}
}

func (_c *MockUnitOfWork_TaskRepository_Call) Run(run func()) *MockUnitOfWork_TaskRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_TaskRepository_Call) Return(taskRepository output.TaskRepository) *MockUnitOfWork_TaskRepository_Call {
	_c.Call.Return(taskRepository)
	return _c
}

func (_c *MockUnitOfWork_TaskRepository_Call) RunAndReturn(run func() output.TaskRepository) *MockUnitOfWork_TaskRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) UserRepository() output.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 output.UserRepository
	if returnFunc, ok := ret.Get(0).(func() output.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(output.UserRepository)
		}
	}
	return r0
}

// MockUnitOfWork_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type MockUnitOfWork_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) UserRepository() *MockUnitOfWork_UserRepository_Call {
	return &MockUnitOfWork_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *MockUnitOfWork_UserRepository_Call) Run(run func()) *MockUnitOfWork_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_UserRepository_Call) Return(userRepository output.UserRepository) *MockUnitOfWork_UserRepository_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockUnitOfWork_UserRepository_Call) RunAndReturn(run func() output.UserRepository) *MockUnitOfWork_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}
