// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/handiism/go-clean-arch-poc/internal/application/dto"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// AssignRole provides a mock function for the type MockUserService
func (_mock *MockUserService) AssignRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*dto.UserOutput, error) {
	ret := _mock.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 *dto.UserOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.UserOutput, error)); ok {
		return returnFunc(ctx, userID, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.UserOutput); ok {
		r0 = returnFunc(ctx, userID, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type MockUserService_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roleID uuid.UUID
func (_e *MockUserService_Expecter) AssignRole(ctx interface{}, userID interface{}, roleID interface{}) *MockUserService_AssignRole_Call {
	return &MockUserService_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, userID, roleID)}
}

func (_c *MockUserService_AssignRole_Call) Run(run func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID)) *MockUserService_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_AssignRole_Call) Return(userOutput *dto.UserOutput, err error) *MockUserService_AssignRole_Call {
	_c.Call.Return(userOutput, err)
	return _c
}

func (_c *MockUserService_AssignRole_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*dto.UserOutput, error)) *MockUserService_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, input dto.CreateUserInput) (*dto.UserOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *dto.UserOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateUserInput) (*dto.UserOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateUserInput) *dto.UserOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateUserInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.CreateUserInput
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, input interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, input)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, input dto.CreateUserInput)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateUserInput
		if args[1] != nil {
			arg1 = args[1].(dto.CreateUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(userOutput *dto.UserOutput, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(userOutput, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, input dto.CreateUserInput) (*dto.UserOutput, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserService
func (_mock *MockUserService) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserService_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserService_DeleteUser_Call {
	return &MockUserService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserService_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_DeleteUser_Call) Return(err error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUser(ctx context.Context, id uuid.UUID) (*dto.UserOutput, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *dto.UserOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.UserOutput, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.UserOutput); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserService_Expecter) GetUser(ctx interface{}, id interface{}) *MockUserService_GetUser_Call {
	return &MockUserService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserService_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUser_Call) Return(userOutput *dto.UserOutput, err error) *MockUserService_GetUser_Call {
	_c.Call.Return(userOutput, err)
	return _c
}

func (_c *MockUserService_GetUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*dto.UserOutput, error)) *MockUserService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByEmail(ctx context.Context, email string) (*dto.UserOutput, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *dto.UserOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.UserOutput, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.UserOutput); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserService_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUserService_GetUserByEmail_Call {
	return &MockUserService_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserService_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) Return(userOutput *dto.UserOutput, err error) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(userOutput, err)
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*dto.UserOutput, error)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockUserService
func (_mock *MockUserService) ListUsers(ctx context.Context, filter dto.UserFilter, pagination dto.Pagination) (*dto.UserListOutput, error) {
	ret := _mock.Called(ctx, filter, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *dto.UserListOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UserFilter, dto.Pagination) (*dto.UserListOutput, error)); ok {
		return returnFunc(ctx, filter, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UserFilter, dto.Pagination) *dto.UserListOutput); ok {
		r0 = returnFunc(ctx, filter, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserListOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.UserFilter, dto.Pagination) error); ok {
		r1 = returnFunc(ctx, filter, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dto.UserFilter
//   - pagination dto.Pagination
func (_e *MockUserService_Expecter) ListUsers(ctx interface{}, filter interface{}, pagination interface{}) *MockUserService_ListUsers_Call {
	return &MockUserService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, filter, pagination)}
}

func (_c *MockUserService_ListUsers_Call) Run(run func(ctx context.Context, filter dto.UserFilter, pagination dto.Pagination)) *MockUserService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UserFilter
		if args[1] != nil {
			arg1 = args[1].(dto.UserFilter)
		}
		var arg2 dto.Pagination
		if args[2] != nil {
			arg2 = args[2].(dto.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_ListUsers_Call) Return(userListOutput *dto.UserListOutput, err error) *MockUserService_ListUsers_Call {
	_c.Call.Return(userListOutput, err)
	return _c
}

func (_c *MockUserService_ListUsers_Call) RunAndReturn(run func(ctx context.Context, filter dto.UserFilter, pagination dto.Pagination) (*dto.UserListOutput, error)) *MockUserService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRole provides a mock function for the type MockUserService
func (_mock *MockUserService) RemoveRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*dto.UserOutput, error) {
	ret := _mock.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRole")
	}

	var r0 *dto.UserOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.UserOutput, error)); ok {
		return returnFunc(ctx, userID, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.UserOutput); ok {
		r0 = returnFunc(ctx, userID, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_RemoveRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRole'
type MockUserService_RemoveRole_Call struct {
	*mock.Call
}

// RemoveRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roleID uuid.UUID
func (_e *MockUserService_Expecter) RemoveRole(ctx interface{}, userID interface{}, roleID interface{}) *MockUserService_RemoveRole_Call {
	return &MockUserService_RemoveRole_Call{Call: _e.mock.On("RemoveRole", ctx, userID, roleID)}
}

func (_c *MockUserService_RemoveRole_Call) Run(run func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID)) *MockUserService_RemoveRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_RemoveRole_Call) Return(userOutput *dto.UserOutput, err error) *MockUserService_RemoveRole_Call {
	_c.Call.Return(userOutput, err)
	return _c
}

func (_c *MockUserService_RemoveRole_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*dto.UserOutput, error)) *MockUserService_RemoveRole_Call {
	_c.Call.Return(run)
	return _c
}

// SeedSystemRoles provides a mock function for the type MockUserService
func (_mock *MockUserService) SeedSystemRoles(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SeedSystemRoles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_SeedSystemRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedSystemRoles'
type MockUserService_SeedSystemRoles_Call struct {
	*mock.Call
}

// SeedSystemRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserService_Expecter) SeedSystemRoles(ctx interface{}) *MockUserService_SeedSystemRoles_Call {
	return &MockUserService_SeedSystemRoles_Call{Call: _e.mock.On("SeedSystemRoles", ctx)}
}

func (_c *MockUserService_SeedSystemRoles_Call) Run(run func(ctx context.Context)) *MockUserService_SeedSystemRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_SeedSystemRoles_Call) Return(err error) *MockUserService_SeedSystemRoles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_SeedSystemRoles_Call) RunAndReturn(run func(ctx context.Context) error) *MockUserService_SeedSystemRoles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateUser(ctx context.Context, id uuid.UUID, input dto.UpdateUserInput) (*dto.UserOutput, error) {
	ret := _mock.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *dto.UserOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateUserInput) (*dto.UserOutput, error)); ok {
		return returnFunc(ctx, id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateUserInput) *dto.UserOutput); ok {
		r0 = returnFunc(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateUserInput) error); ok {
		r1 = returnFunc(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input dto.UpdateUserInput
func (_e *MockUserService_Expecter) UpdateUser(ctx interface{}, id interface{}, input interface{}) *MockUserService_UpdateUser_Call {
	return &MockUserService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, input)}
}

func (_c *MockUserService_UpdateUser_Call) Run(run func(ctx context.Context, id uuid.UUID, input dto.UpdateUserInput)) *MockUserService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.UpdateUserInput
		if args[2] != nil {
			arg2 = args[2].(dto.UpdateUserInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateUser_Call) Return(userOutput *dto.UserOutput, err error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(userOutput, err)
	return _c
}

func (_c *MockUserService_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, input dto.UpdateUserInput) (*dto.UserOutput, error)) *MockUserService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
