// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiresAt    time.Time `json:"expiresAt"`
	User         *User     `json:"user"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CreateLabelInput struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type CreateTaskInput struct {
	Title       string      `json:"title"`
	Description *string     `json:"description,omitempty"`
	Priority    *Priority   `json:"priority,omitempty"`
	DueDate     *time.Time  `json:"dueDate,omitempty"`
	AssigneeID  *uuid.UUID  `json:"assigneeId,omitempty"`
	LabelIds    []uuid.UUID `json:"labelIds,omitempty"`
}

type Label struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"createdAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PaginationInput struct {
	Page     *int    `json:"page,omitempty"`
	PageSize *int    `json:"pageSize,omitempty"`
	SortBy   *string `json:"sortBy,omitempty"`
	SortDesc *bool   `json:"sortDesc,omitempty"`
}

type Permission struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Resource string    `json:"resource"`
	Action   string    `json:"action"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type Role struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	Permissions []*Permission `json:"permissions"`
	CreatedAt   time.Time     `json:"createdAt"`
}

type Subscription struct {
}

type Task struct {
	ID          uuid.UUID         `json:"id"`
	Title       string            `json:"title"`
	Description *string           `json:"description,omitempty"`
	Status      TaskStatus        `json:"status"`
	Priority    Priority          `json:"priority"`
	DueDate     *time.Time        `json:"dueDate,omitempty"`
	Assignee    *User             `json:"assignee,omitempty"`
	Creator     *User             `json:"creator"`
	Labels      []*Label          `json:"labels"`
	Attachments []*TaskAttachment `json:"attachments"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

type TaskAttachment struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"taskId"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"contentType"`
	SizeBytes   int       `json:"sizeBytes"`
	UploadedBy  uuid.UUID `json:"uploadedBy"`
	CreatedAt   time.Time `json:"createdAt"`
}

type TaskAttachmentDownload struct {
	Attachment    *TaskAttachment `json:"attachment"`
	ContentBase64 string          `json:"contentBase64"`
}

type TaskConnection struct {
	Edges      []*TaskEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type TaskEdge struct {
	Node   *Task  `json:"node"`
	Cursor string `json:"cursor"`
}

type TaskFilter struct {
	Status     *TaskStatus `json:"status,omitempty"`
	Priority   *Priority   `json:"priority,omitempty"`
	AssigneeID *uuid.UUID  `json:"assigneeId,omitempty"`
	CreatorID  *uuid.UUID  `json:"creatorId,omitempty"`
	LabelIds   []uuid.UUID `json:"labelIds,omitempty"`
	Search     *string     `json:"search,omitempty"`
	DueBefore  *time.Time  `json:"dueBefore,omitempty"`
	DueAfter   *time.Time  `json:"dueAfter,omitempty"`
}

type UpdateLabelInput struct {
	Name  *string `json:"name,omitempty"`
	Color *string `json:"color,omitempty"`
}

type UpdateTaskInput struct {
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	Priority    *Priority  `json:"priority,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
}

type UpdateUserInput struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Roles     []*Role   `json:"roles"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor string `json:"cursor"`
}

type UserFilter struct {
	Search *string    `json:"search,omitempty"`
	RoleID *uuid.UUID `json:"roleId,omitempty"`
}

type Priority string

const (
	PriorityLow    Priority = "LOW"
	PriorityMedium Priority = "MEDIUM"
	PriorityHigh   Priority = "HIGH"
	PriorityUrgent Priority = "URGENT"
)

var AllPriority = []Priority{
	PriorityLow,
	PriorityMedium,
	PriorityHigh,
	PriorityUrgent,
}

func (e Priority) IsValid() bool {
	switch e {
	case PriorityLow, PriorityMedium, PriorityHigh, PriorityUrgent:
		return true
	}
	return false
}

func (e Priority) String() string {
	return string(e)
}

func (e *Priority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Priority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Priority", str)
	}
	return nil
}

func (e Priority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "TODO"
	TaskStatusInProgress TaskStatus = "IN_PROGRESS"
	TaskStatusInReview   TaskStatus = "IN_REVIEW"
	TaskStatusDone       TaskStatus = "DONE"
	TaskStatusArchived   TaskStatus = "ARCHIVED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusTodo,
	TaskStatusInProgress,
	TaskStatusInReview,
	TaskStatusDone,
	TaskStatusArchived,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusTodo, TaskStatusInProgress, TaskStatusInReview, TaskStatusDone, TaskStatusArchived:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
