package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/handiism/go-clean-arch-poc/internal/application/dto"
	"github.com/handiism/go-clean-arch-poc/internal/auth"
	"github.com/handiism/go-clean-arch-poc/internal/domain/entity"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	authOutput, err := r.authService.Login(ctx, dto.LoginInput{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return authToGraphQL(authOutput), nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*AuthPayload, error) {
	authOutput, err := r.authService.Register(ctx, dto.CreateUserInput{
		Email:    input.Email,
		Password: input.Password,
		Name:     input.Name,
	})
	if err != nil {
		return nil, err
	}
	return authToGraphQL(authOutput), nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*AuthPayload, error) {
	authOutput, err := r.authService.RefreshToken(ctx, refreshToken)
	if err != nil {
		return nil, err
	}
	return authToGraphQL(authOutput), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	token := auth.GetTokenFromContext(ctx)
	if err := r.authService.Logout(ctx, claims.UserID, token); err != nil {
		return false, err
	}
	return true, nil
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input CreateTaskInput) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	priority := string(PriorityMedium)
	if input.Priority != nil {
		priority = string(*input.Priority)
	}
	taskInput := dto.CreateTaskInput{
		Title:    input.Title,
		Priority: priority,
		LabelIDs: input.LabelIds,
	}
	if input.Description != nil {
		taskInput.Description = *input.Description
	}
	if input.DueDate != nil {
		taskInput.DueDate = input.DueDate
	}
	if input.AssigneeID != nil {
		taskInput.AssigneeID = input.AssigneeID
	}

	task, err := r.taskService.CreateTask(ctx, taskInput)
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id uuid.UUID, input UpdateTaskInput) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	updateInput := dto.UpdateTaskInput{}
	if input.Title != nil {
		updateInput.Title = input.Title
	}
	if input.Description != nil {
		updateInput.Description = input.Description
	}
	if input.Priority != nil {
		p := string(*input.Priority)
		updateInput.Priority = &p
	}
	if input.DueDate != nil {
		updateInput.DueDate = input.DueDate
	}

	task, err := r.taskService.UpdateTask(ctx, id, updateInput)
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id uuid.UUID) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	if err := r.taskService.DeleteTask(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// AssignTask is the resolver for the assignTask field.
func (r *mutationResolver) AssignTask(ctx context.Context, id uuid.UUID, assigneeID uuid.UUID) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	task, err := r.taskService.AssignTask(ctx, id, assigneeID)
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// UnassignTask is the resolver for the unassignTask field.
func (r *mutationResolver) UnassignTask(ctx context.Context, id uuid.UUID) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	task, err := r.taskService.UnassignTask(ctx, id)
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// ChangeTaskStatus is the resolver for the changeTaskStatus field.
func (r *mutationResolver) ChangeTaskStatus(ctx context.Context, id uuid.UUID, status TaskStatus) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	task, err := r.taskService.ChangeTaskStatus(ctx, id, string(status))
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// AddLabelToTask is the resolver for the addLabelToTask field.
func (r *mutationResolver) AddLabelToTask(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	task, err := r.taskService.AddLabel(ctx, taskID, labelID)
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// RemoveLabelFromTask is the resolver for the removeLabelFromTask field.
func (r *mutationResolver) RemoveLabelFromTask(ctx context.Context, taskID uuid.UUID, labelID uuid.UUID) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	task, err := r.taskService.RemoveLabel(ctx, taskID, labelID)
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input UpdateUserInput) (*User, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	updateInput := dto.UpdateUserInput{}
	if input.Email != nil {
		updateInput.Email = input.Email
	}
	if input.Name != nil {
		updateInput.Name = input.Name
	}
	user, err := r.userService.UpdateUser(ctx, id, updateInput)
	if err != nil {
		return nil, err
	}
	return userToGraphQL(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	if err := r.userService.DeleteUser(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*User, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	user, err := r.userService.AssignRole(ctx, userID, roleID)
	if err != nil {
		return nil, err
	}
	return userToGraphQL(user), nil
}

// RemoveRole is the resolver for the removeRole field.
func (r *mutationResolver) RemoveRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) (*User, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	user, err := r.userService.RemoveRole(ctx, userID, roleID)
	if err != nil {
		return nil, err
	}
	return userToGraphQL(user), nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input ChangePasswordInput) (bool, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	if err := r.authService.ChangePassword(ctx, claims.UserID, dto.ChangePasswordInput{
		OldPassword: input.OldPassword,
		NewPassword: input.NewPassword,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input CreateLabelInput) (*Label, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	if err := r.requireAnyRole(ctx, entity.RoleAdmin, entity.RoleManager); err != nil {
		return nil, err
	}
	label, err := r.labelService.CreateLabel(ctx, dto.CreateLabelInput{
		Name:  input.Name,
		Color: input.Color,
	})
	if err != nil {
		return nil, err
	}
	return labelToGraphQL(label), nil
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, id uuid.UUID, input UpdateLabelInput) (*Label, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	if err := r.requireAnyRole(ctx, entity.RoleAdmin, entity.RoleManager); err != nil {
		return nil, err
	}
	updateInput := dto.UpdateLabelInput{}
	if input.Name != nil {
		updateInput.Name = input.Name
	}
	if input.Color != nil {
		updateInput.Color = input.Color
	}
	label, err := r.labelService.UpdateLabel(ctx, id, updateInput)
	if err != nil {
		return nil, err
	}
	return labelToGraphQL(label), nil
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id uuid.UUID) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	if err := r.requireAnyRole(ctx, entity.RoleAdmin, entity.RoleManager); err != nil {
		return false, err
	}
	if err := r.labelService.DeleteLabel(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id uuid.UUID) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	task, err := r.taskService.GetTask(ctx, id)
	if err != nil {
		return nil, err
	}
	return r.enrichAndMapTask(ctx, task)
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, filter *TaskFilter, pagination *PaginationInput) (*TaskConnection, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	taskFilter := dto.TaskFilter{}
	if filter != nil {
		if filter.Status != nil {
			s := string(*filter.Status)
			taskFilter.Status = &s
		}
		if filter.Priority != nil {
			p := string(*filter.Priority)
			taskFilter.Priority = &p
		}
		if filter.AssigneeID != nil {
			taskFilter.AssigneeID = filter.AssigneeID
		}
		if filter.CreatorID != nil {
			taskFilter.CreatorID = filter.CreatorID
		}
		if filter.LabelIds != nil {
			taskFilter.LabelIDs = filter.LabelIds
		}
		if filter.Search != nil {
			taskFilter.Search = *filter.Search
		}
	}

	list, err := r.taskService.ListTasks(ctx, taskFilter, paginationFromInput(pagination))
	if err != nil {
		return nil, err
	}

	// Eagerly enrich tasks with users
	tasks := make([]*Task, 0, len(list.Tasks))
	for _, t := range list.Tasks {
		task, err := r.enrichAndMapTask(ctx, t)
		if err != nil {
			return nil, err
		}
		tasks = append(tasks, task)
	}

	edges := make([]*TaskEdge, 0, len(tasks))
	for i, task := range tasks {
		cursor := encodeCursor(i + 1 + (list.Page-1)*list.PageSize)
		edges = append(edges, &TaskEdge{
			Node:   task,
			Cursor: cursor,
		})
	}

	return &TaskConnection{
		Edges:      edges,
		PageInfo:   pageInfoFromPagination(list.Page, list.PageSize, list.TotalPages, int(list.Total)),
		TotalCount: int(list.Total),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	claims, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.userService.GetUser(ctx, claims.UserID)
	if err != nil {
		return nil, err
	}
	return userToGraphQL(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*User, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	user, err := r.userService.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return userToGraphQL(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filter *UserFilter, pagination *PaginationInput) (*UserConnection, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	userFilter := dto.UserFilter{}
	if filter != nil {
		if filter.Search != nil {
			userFilter.Search = *filter.Search
		}
		if filter.RoleID != nil {
			userFilter.RoleID = filter.RoleID
		}
	}

	list, err := r.userService.ListUsers(ctx, userFilter, paginationFromInput(pagination))
	if err != nil {
		return nil, err
	}
	return userConnectionToGraphQL(list), nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*Role, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	roles, err := r.roleService.ListRoles(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*Role, 0, len(roles))
	for _, role := range roles {
		result = append(result, roleToGraphQL(role))
	}
	return result, nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id uuid.UUID) (*Role, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	role, err := r.roleService.GetRole(ctx, id)
	if err != nil {
		return nil, err
	}
	return roleToGraphQL(role), nil
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context) ([]*Label, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	labels, err := r.labelService.ListLabels(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*Label, 0, len(labels))
	for _, label := range labels {
		result = append(result, labelToGraphQL(label))
	}
	return result, nil
}

// TaskCreated is the resolver for the taskCreated field.
func (r *subscriptionResolver) TaskCreated(ctx context.Context) (<-chan *Task, error) {
	return nil, fmt.Errorf("subscriptions not implemented")
}

// TaskUpdated is the resolver for the taskUpdated field.
func (r *subscriptionResolver) TaskUpdated(ctx context.Context, id *uuid.UUID) (<-chan *Task, error) {
	return nil, fmt.Errorf("subscriptions not implemented")
}

// TaskDeleted is the resolver for the taskDeleted field.
func (r *subscriptionResolver) TaskDeleted(ctx context.Context) (<-chan uuid.UUID, error) {
	return nil, fmt.Errorf("subscriptions not implemented")
}

// TaskAssigned is the resolver for the taskAssigned field.
func (r *subscriptionResolver) TaskAssigned(ctx context.Context, assigneeID *uuid.UUID) (<-chan *Task, error) {
	return nil, fmt.Errorf("subscriptions not implemented")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
