// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acl.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createACLEntry = `-- name: CreateACLEntry :one
INSERT INTO acl_entries (
    id, resource_type, resource_id, subject_type, subject_id, permission, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, resource_type, resource_id, subject_type, subject_id, permission, created_at
`

type CreateACLEntryParams struct {
	ID           uuid.UUID `json:"id"`
	ResourceType string    `json:"resourceType"`
	ResourceID   uuid.UUID `json:"resourceId"`
	SubjectType  string    `json:"subjectType"`
	SubjectID    uuid.UUID `json:"subjectId"`
	Permission   string    `json:"permission"`
	CreatedAt    time.Time `json:"createdAt"`
}

func (q *Queries) CreateACLEntry(ctx context.Context, arg CreateACLEntryParams) (AclEntry, error) {
	row := q.db.QueryRow(ctx, createACLEntry,
		arg.ID,
		arg.ResourceType,
		arg.ResourceID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Permission,
		arg.CreatedAt,
	)
	var i AclEntry
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const deleteACLEntriesByResource = `-- name: DeleteACLEntriesByResource :exec
DELETE FROM acl_entries
WHERE resource_type = $1 AND resource_id = $2
`

type DeleteACLEntriesByResourceParams struct {
	ResourceType string    `json:"resourceType"`
	ResourceID   uuid.UUID `json:"resourceId"`
}

func (q *Queries) DeleteACLEntriesByResource(ctx context.Context, arg DeleteACLEntriesByResourceParams) error {
	_, err := q.db.Exec(ctx, deleteACLEntriesByResource, arg.ResourceType, arg.ResourceID)
	return err
}

const deleteACLEntry = `-- name: DeleteACLEntry :exec
DELETE FROM acl_entries
WHERE id = $1
`

func (q *Queries) DeleteACLEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteACLEntry, id)
	return err
}

const getACLEntriesByResource = `-- name: GetACLEntriesByResource :many
SELECT id, resource_type, resource_id, subject_type, subject_id, permission, created_at FROM acl_entries
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at
`

type GetACLEntriesByResourceParams struct {
	ResourceType string    `json:"resourceType"`
	ResourceID   uuid.UUID `json:"resourceId"`
}

func (q *Queries) GetACLEntriesByResource(ctx context.Context, arg GetACLEntriesByResourceParams) ([]AclEntry, error) {
	rows, err := q.db.Query(ctx, getACLEntriesByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AclEntry{}
	for rows.Next() {
		var i AclEntry
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getACLEntriesBySubject = `-- name: GetACLEntriesBySubject :many
SELECT id, resource_type, resource_id, subject_type, subject_id, permission, created_at FROM acl_entries
WHERE subject_type = $1 AND subject_id = $2
ORDER BY created_at
`

type GetACLEntriesBySubjectParams struct {
	SubjectType string    `json:"subjectType"`
	SubjectID   uuid.UUID `json:"subjectId"`
}

func (q *Queries) GetACLEntriesBySubject(ctx context.Context, arg GetACLEntriesBySubjectParams) ([]AclEntry, error) {
	rows, err := q.db.Query(ctx, getACLEntriesBySubject, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AclEntry{}
	for rows.Next() {
		var i AclEntry
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ResourceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getACLEntry = `-- name: GetACLEntry :one
SELECT id, resource_type, resource_id, subject_type, subject_id, permission, created_at FROM acl_entries
WHERE id = $1
`

func (q *Queries) GetACLEntry(ctx context.Context, id uuid.UUID) (AclEntry, error) {
	row := q.db.QueryRow(ctx, getACLEntry, id)
	var i AclEntry
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.ResourceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS(
    SELECT 1 FROM acl_entries
    WHERE resource_type = $1 
      AND resource_id = $2 
      AND subject_type = $3 
      AND subject_id = $4 
      AND (permission = $5 OR permission = 'admin')
)
`

type HasPermissionParams struct {
	ResourceType string    `json:"resourceType"`
	ResourceID   uuid.UUID `json:"resourceId"`
	SubjectType  string    `json:"subjectType"`
	SubjectID    uuid.UUID `json:"subjectId"`
	Permission   string    `json:"permission"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission,
		arg.ResourceType,
		arg.ResourceID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Permission,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
